### ISSUE TITLE
 Increasing default timeout for druid introspection

### ISSUE THREAD

**Issue by indrekj** [allegro/turnilo#101]
This is from: https://github.com/yahoo/swiv/issues/21 . It looks like we have the same issue using turnilo.

Starting turnilo puts quite a lot of load to historical and then times out. This only happens on our production servers, but not in our testing servers. This is probably because production has a lot more segements to analyse.

**Comment by mkuthan** [comment]
Hi @indrekj 

Thank you for reporting. We did not observe this kind of issues on our cluster (~ 100k segments). But for sure this timeout should be configurable in Turnilo. Right now we do not have plans to resolve this issue but we are open for contribution :)

**Comment by Laboltus** [comment]
Hi. I guess we faced with the same issue and I found the reason. Please see the explanation here https://github.com/apache/incubator-druid/pull/5489.

**Comment by indrekj** [comment]
@Laboltus I think you're correct. Worked fine with a newer druid version.
