### ISSUE TITLE
What is the way to hide the default measures coming from druid cube?

### ISSUE THREAD

**Issue by swati-sujay** [allegro/turnilo#1069]
I want to derive the measures based on the metrics coming in the druid data cube and hide all the default measures. 

adding attribute `hidden: true ` against the measure does not solve this. Any suggestion or work around for this problem?

**Comment by adrianmroz-allegro** [comment]
https://turnilo.slack.com/archives/CEQMX06NB/p1683021261981699

**Comment by Konstantinos-Chaitas-PubNative** [comment]
@adrianmroz-allegro can you please post here the answer? Slack messages are only available for 90 days. Thanks!
