### ISSUE TITLE
Legend view does not work for charts split on dimensions filtered in contains or regex mode

### ISSUE THREAD

**Issue by piter75** [allegro/turnilo#110]
Line chart's legend is empty with "wiki" cube when:
 - filtered on "Channel" dimmension in either "contains" or "regex" mode with single character "e"
 - split on "Channel" and "Time" dimensions

Legend should contain top 100 values containing "e" character instead.

[Reproduce link](http://localhost:9090/#wiki/3/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5VIazBrosuAuYCMAETNadhOjEUPRMIcSa+KSeAL4AujEMav7cITQQ2ADmkobGBFRw2CQIknDkGDjc5DhocBlKTGCIMMEqIFxxTNiY9HhSiFDE8WGaSGh2DhraqWjpWZLWEGzYUG5V1EXEJWGYdPigudxw1tbE1gsQhuVrBKdQ5MTYi/OJhEsQvdgwCAiJydO6Jb6RxAlY3ZhAySZFxfBC0D7qbjmESeAASkigu16ByMJkhTEWVwq7hAcHuj2e2VeSBYH3wsN+nRAbDJzlaeFA0AAst8MPhZi0whlMggAsdTucmCxeRA2tUYNh6AkmJoMiRrN5QascBMmarNtYAMpYo4nM6SUWZCn7EHLbUkgqbbZvWm9ACsr0oEEylCQPs+31+QA)

**Comment by l2dy** [comment]
Any progress on this?

**Comment by l2dy** [comment]
Bumped into this issue recently, can you take a look? @adrianmroz

**Comment by adrianmroz** [comment]
After 1.12 release :)

**Comment by adrianmroz** [comment]
https://github.com/allegro/turnilo/blob/master/src/client/components/dimension-tile/dimension-tile.tsx#L456

Here, code assumes the it's include filter. We need to dispatch matcher based on `filterClause.action`.
