### ISSUE TITLE
defaultSelectedMeasures does not set first 4 measures

### ISSUE THREAD

**Issue by jamangstangs** [allegro/turnilo#1108]
https://github.com/allegro/turnilo/blob/1895141bfde2252bcd0db25b0754d601cc99d317/src/common/models/data-cube/data-cube.ts#L515-L521

In [turnilo docs](https://allegro.github.io/turnilo/configuration-datacubes.html#basic-data-cube-properties), defaultSelectedMeasures default value is first four measures. 
But, defaultSelectedMeasures is always initialized as an empty array, so the first4Measures section can never be called.
```
if (dataCube.defaultSelectedMeasures.length > 0) {
```

**Comment by adrianmroz** [comment]
Looks like you have fix ready, feel free to create a PR :)
