### ISSUE TITLE
Parse error while attempting to connect to druid broker

### ISSUE THREAD

**Issue by a2l007** [allegro/turnilo#126]
I'm attempting to connect Turnilo to my druid broker but I get the following Parse Error:
```
turnilo --druid druid-broker132.hostname.com:4443
Starting Turnilo v1.4.2
Adding cluster manager for 'druid' with 0 dataCubes
Turnilo is listening on address :: port 9090
Failed to connect to cluster 'druid' because: Error: Parse Error (will retry in 19859ms)
```
The config generation command fails as well:
```
turnilo --druid druid-broker132.hostname.com:4443  --print-config --with-comments > config.yaml
There was an error generating a config: Could not find any data cubes, please verify network connectivity
```

I have confirmed that I'm able to connect to the broker host from the host from which I'm running Turnilo. Any suggestions on what could be wrong here?

**Comment by a2l007** [comment]
@mkuthan I have fixed this issue and would like to contribute the fix. Would I have to sign a CLA before the code can be merged?

**Comment by mkuthan** [comment]
@a2l007, excellently - create pull request please, we will glad to review and merge. CLA is not needed.
