### ISSUE TITLE
Multi value dimensions filtered on some values and then split should not contain values not present in filter

### ISSUE THREAD

**Issue by piter75** [allegro/turnilo#143]
Currently filtering a cube with some values from multi value dimension and then splitting on the same dimension displays a list of all values present in filtered rows for that dimension.

While the cause of this behaviour is quite understandable it is counterintuitive as user expects to see only values selected in filter the same way it works for filters on all other dimension types.

**Comment by adrianmroz** [comment]
Closed with #455
