### ISSUE TITLE
Allow histogram parameters tuning for quantile measures

### ISSUE THREAD

**Issue by piter75** [allegro/turnilo#15]
Current implementation of plywood does not allow tuning of parameters for approximate histogram in quantile expressions.

It should be possible to use following expression:
$main.quantile($a_histogram,0.98,'resolution=100,numBuckets=11,lowerLimit=0,upperLimit=1000')

This issue should be resolved with #10 but needs to be verified.

**Comment by mkuthan** [comment]
Fixed in #17
