### ISSUE TITLE
Measure value is not visible when measure is not present in all data points

### ISSUE THREAD

**Issue by erykpiast** [allegro/turnilo#180]
I have data with some measure available (lets say "alcohol volume") for part of data points only. When I split the data by some dimension ("drink type"), I have one set of points with the measure (lets say "booze") and another without it ("water"). When I add another split (ex. by time) I'd like to see alcohol volume visualized for booze, even if it's not available for the water. Currently I see nothing at all, what makes me terribly sad.

![screen shot 2018-08-29 at 14 42 14](https://user-images.githubusercontent.com/1434406/44788234-cb107700-ab99-11e8-848d-5ecec91ef69a.png)

I can see backend returns measure value for booze and `"NaN"` for water, so it's obvious fault of frontend code.

**Comment by adrianmroz** [comment]
Missing data is represented as `"NaN"` instead of `NaN` and `d3.extend`, `d3.min`, `d3.max` don't calculate proper extent for chart. Because extent is invalid, so is scale and we can't draw chart lines.

**Comment by erykpiast** [comment]
You’re excused, then!

**Comment by adrianmroz** [comment]
Not really, NaN is not a part of JSON spec, so we need to convert that on the frontend.
