### ISSUE TITLE
Resizable columns for table view

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#183]
Proposals:
- ability to resize left part of the table view
- strong visual separation between dimensions and measures cells

**Comment by adrianmroz** [comment]
Right now, long dimension values don't fit into left column. Should be resizable.
Also measure names can get long too, so each column should be resizable.

**Comment by olgen** [comment]
Guys, is this sth you plan on working on in the near future? Looks like 1.10 and 1.12 are closed already?

**Comment by adrianmroz** [comment]
It was pushed out of previous milestones and for sure it's not planned for 1.13.

**Comment by cedrics** [comment]
Hey, we are thinking about building this ourselves as we need the feature. Anything we should keep in mind before tackling this? Wanted to ask beforehand so we don't run into any blockers that prevents merging it from your side 😸

**Comment by adrianmroz** [comment]
Ugh, I don't think so, but on the other hand we didn't look into this specifically. 

Big problem is that Table (and lot of other viz components) use `Scroller` component that eats most of the events. I imagine for table there will be some draggable div on top of scroller that would on each drag update `leftColumnWidth` (or something) prop on table. In table `Scrollers` gets layout, now it has to be dynamic. And `calculateMousePosition` must be aware of dynamic widths. 

Anyway, we will appreciate any help there!
