### ISSUE TITLE
Use either Promise, Q.Promise or other Promise library consistently

### ISSUE THREAD

**Issue by piter75** [allegro/turnilo#19]
During the upgrade to Plywood 0.17.x **some** Q.Promise uses have been refactored to native ES6 Promises because Plywood moved to native Promises.

Some of the uses have been left intact to not extend the dependencies upgrade to a big refactoring.
Because of this the usage of Promises is now inconsistent.

We should evaluate the options to use either native Promise (which are quite basic), [Q.Promise](https://www.npmjs.com/package/q) or maybe even [BlueBird](https://www.npmjs.com/package/bluebird) - which are far more advanced and can accept or replace native Promises.

**Comment by piter75** [comment]
A nice writeup about native vs. BlueBird can be found [here](https://stackoverflow.com/a/34961040)

**Comment by milimetric** [comment]
Hi.  I'm looking to do some light work on Turnilo in my spare time.  I looked around for a good issue to work on, and this seemed useful and unassigned.  I'll try to fix it unless someone says otherwise.

**Comment by adrianmroz** [comment]
Hi. It's fantastic! Feel free to ask any questions here.

Native promises and fetch should suffice. But as you said, if we hit roadblock we can discuss solution here. For example in filter-tile.tsx Q.Promise is used as a glorified callback registration. I'm more or less working on this part of app right now and still didn't figure out better solution.
