### ISSUE TITLE
Avoid using bind multiple times

### ISSUE THREAD

**Issue by pwolaq** [allegro/turnilo#203]
I have noticed that there are many places* where bind is used in render method, creating a new function on every invocation. This results in unnecessary memory pollution and re-renders, as a result affecting performance.

A proper approach would be to either:
- Use class property syntax with Babel, or
- Bind every method *once* in constructor

\* few examples:
- https://github.com/allegro/turnilo/blob/master/src/client/views/cube-view/cube-view.tsx#L367
- https://github.com/allegro/turnilo/blob/master/src/client/views/home-view/home-header-bar/home-header-bar.tsx#L68
- https://github.com/allegro/turnilo/blob/master/src/client/components/clearable-input/clearable-input.tsx#L64

**Comment by adrianmroz** [comment]
Hi!

Valid concern and we should gradually fix this. In my opinion we should use class property syntax. Feels better. 

Feel free to submit any changes on that matter!
