### ISSUE TITLE
Resolve vulnerabilities

### ISSUE THREAD

**Issue by pwolaq** [allegro/turnilo#208]
Running `npm audit` shows that the project contains 9 vulnerabilities (4 moderate and 5 high).

They can be resolved by updating `node-sass` and `sshpk`.

**Comment by adrianmroz** [comment]
https://github.com/sass/node-sass/pull/2170

node-sass has kinda faux vulnerability and they refuse to update request package in 4.x.

**Comment by mkuthan** [comment]
Any progress with vulnerability fixes in dependencies?

**Comment by adrianmroz** [comment]
node-sass is still problematic but we should be able to reduce faulty deps

**Comment by adrianmroz** [comment]
Check https://github.com/naugtur/npm-audit-resolver to resolve vulnerable deps with better granularity.

**Comment by l2dy** [comment]
@adrianmroz Should this issue be closed now?

**Comment by adrianmroz** [comment]
Yup! We can reopen if npm finds something.
