### ISSUE TITLE
New UI for selecting measures

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#216]
- [x] "Series" row below Splits for dropping Measures
- [x] "Add" button for Filters, Splits, Series with BubbleMenu presenting all appropriate measures/dimensions with option to filter them.
- [x] Remove Checkboxes beside Measures
- [x] Action menu for Measures like for Dimensions. (Add, Replace, Filter)
- [x] New ViewDefinition version and update of converters. Now we should keep measures in ViewDefinition as List of objects. For this task, object should keep just the reference to measure
- [x] Change of colours - Measures and Dimension should have different colours. All dimension should have same colour.

**Comment by mkuthan** [comment]
As long as only measures could be added to series row I would keep the row name "measures". But this is a subject for discussion.
