### ISSUE TITLE
Measure formatters

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#217]
Each measure should have one defined formatter in config. If not, we use default formatter defined in application. When editing Measure options in UI, we can pick between this formatting, exact (only if it's different than first one), percent (`0[.]00%`) and Custom (number formatting string).

Formatting should be applied everywhere in UI.

We should use appropriate time formatter for measures with milliseconds instead of dividing these values by hand.

**Comment by mkuthan** [comment]
We could also consider selector for data type (like ms or sec) and provide formatter for that type. It would encapsulate numbro formatting somehow. Very similar formatting method is used by Grafana for Axis scale units.

**Comment by adrianmroz** [comment]
We can't inspect kind of measure, they're just numbers. If we give option to format as time to all measures it could look clunky. I think owner of datacube should set proper default for time measures and/or user could use custom formatter.

**Comment by l2dy** [comment]
How can I define a formatter (e.g. percent) for a measure in config? Didn't find it in https://github.com/allegro/turnilo/blob/1.11.0/docs/configuration.md.

**Comment by adrianmroz** [comment]
Oh, that's a mistake! We need add that to documentation. For now - it's "format" key in measure and it's string of numbro formatting options - the same you can write inside measure menu popover.
