### ISSUE TITLE
Histogram measures

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#219]
Histograms should be special measures. 

- [ ] ~~In config they should be defined as such. No formula, but field for type, reference to underlying measure and default percentile.~~
- [x] In UI user should be able to define what percentile he likes to calculate. At start is set to default value.
- [x] It is possible to add multiple histograms to Series. If you try to add second histogram with the same percentile, "OK" action should be disabled thus user need to provide different percentile to apply measure.
- [x] Tune parameters (resolution, numBuckets, lowerLimit, upperLimit) are taken from Data Cube config

**Comment by l2dy** [comment]
> Histograms should be special measures.
> 
>  * [ ]  In config they should be defined as such. No formula, but field for type, reference to underlying measure and default percentile.

Can you provide an example of the quantile series config in configuration.md?

**Comment by adrianmroz** [comment]
You got me! 

We didn't update this task after changing requirements. Percentiles are defined like they were before and turnilo when encounters `quantile` expression does its magic. So no changes to configuration needed. One caveat - you can't have quantile expression inside another expression. If you define measure as `$main.quantile(foo) * 100`, turnilo will treat it as simple measure.

**Comment by l2dy** [comment]
@adrianmroz Good idea, but magic should be documented!

Another question, would `$main.quantile(foo * 100)` be treated as a quantile measure?

**Comment by adrianmroz** [comment]
- [ ] Documentation for quantile series

- [ ] (optional) Add percentile to wiki data cube.

**Comment by adrianmroz** [comment]
Yup, I'll try to add something to documentation. 

> Another question, would `$main.quantile(foo * 100)` be treated as a quantile measure?

Actually I'm not sure. Could work. Another question is if it should? I think that arithmetic operations on histograms is dangerous. Multiply by 100 not so much, but combining two measures is almost meaningless. Right now, check are rudimentary, not bullet proof :)
