### ISSUE TITLE
Better documentation, organized with chapters, with search etc.

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#226]
Right now the documentation is organized as a few separate markdown files. The most important part of the Turnilo configuration is defined within single huge file without table of content or search capabilities.

It would be nice to have documentation organized with chapters, with search capabilities, etc.

Proposals:
https://docs.gitbook.com/
https://help.github.com/articles/about-github-wikis/

**Comment by trtg** [comment]
@mkuthan I might be interested in helping, while I work through my comparison with Pivot.

**Comment by mkuthan** [comment]
@adrianmroz - GitHub Actions are done, so now I would like to improve documentation. Make some space for discussion on the next grooming, please :)

**Comment by mkuthan** [comment]
Closed in #720, there is no search but at least we have separated pages with TOCs
