### ISSUE TITLE
Display druid query for Wikipedia example is broken

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#245]
Error:
```
Client Error: {"message":"Uncaught Error: must filter on time unless the allowEternity flag is set","file":"http://10.101.1.42:9090/main.js?v=1.9.1","line":40,"column":48239,"stack":"Error: must filter on time unless the allowEternity flag is set\n    at e.timeFilterToIntervals (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:275268)\n    at e.filterToDruid (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:275013)\n    at n.getQueryAndPostTransform (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:313239)\n    at n.e.simulateValue (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:257596)\n    at http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:151848\n    at n.fillDatasetExternalAlterations (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:115504)\n    at n.fillExpressionExternalAlteration (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:115208)\n    at http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:151811\n    at n.e._computeResolvedSimulate (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:152023)\n    at n.e.simulateQueryPlan (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:151495)"},"sometimeLater":"2016-09-12T06:48:00Z","channel":"vi","cityName":null,"comment":"fix using [[Project:AWB|AWB]]","commentLength":29,"countryI
```

_Originally posted by @trtg in https://github.com/allegro/turnilo/issues/68#issuecomment-441809049_

**Comment by adrianmroz** [comment]
Druid Query modal should be disabled for native clusters.

**Comment by trtg** [comment]
Not sure I follow- could you clarify what you mean by a native cluster? The display query modal does work with a dataset I generated myself (surprisingly) but so far not with the wikipedia dataset.

**Comment by adrianmroz** [comment]
Sure, for me it's cluster based on JSON file in contrast do cluster with Druid instance behind it. This distinction is in the code but unfortunately is not explicit. 

Because such cluster doesn't really queries Druid instance it's meaningless to simulate such Druid query - it could confuse user. Of course, it's possible to generate such query with right circumstances. If your DataCube has attributes that are in line with requirements for DataCube with Druid cluster, such query plan could be simulated. But as I said, this query is not run anywhere. Plywood queries JSON files differently.
