### ISSUE TITLE
Filter value is no longer visible in tile

### ISSUE THREAD

**Issue by michalmisiewicz** [allegro/turnilo#252]
After upgrading turnilo from version 1.8.1 to 1.10.0 filter value in tile is no longer visible.
1.8.1  
![screenshot from 2018-12-11 10-54-28](https://user-images.githubusercontent.com/16355374/49793524-b8c7dc80-fd35-11e8-9d63-47461e5bb091.png)
1.10.0  
![screenshot from 2018-12-11 10-53-42](https://user-images.githubusercontent.com/16355374/49793521-b5ccec00-fd35-11e8-96f4-5a52d8fac11d.png)

**Comment by adrianmroz** [comment]
Turnilo UI doesn't support correctly true boolean dimensions. It treats them as String dictionaries and in the end creates StringFilterClause.

**Comment by adrianmroz** [comment]
Turnilo shouldn't handle real booleans as values because Druid doesn't support them. We should change example to use dictionary.

**Comment by adrianmroz** [comment]
Resolved in #259
