### ISSUE TITLE
Connect to a Druid cluster with Kerberos/SPNEGO

### ISSUE THREAD

**Issue by elukey** [allegro/turnilo#263]
Hi everybody,

first of all thanks for all the awesome work that you are doing with Turnilo. I am wondering if it can support connecting to a kerberized Druid cluster via HTTP/SPNEGO, or if this is something that needs to be implemented (didn't find anything in the docs).

**Comment by mkuthan** [comment]
Turnilo does not support secured Druid cluster at all. You could try with AuthToken header defined for all Druid requests. See corresponding Plywood libraries used for communication with Druid cluster:

https://github.com/implydata/plywood-base-api/blob/fb529bc04e900c9540207976dbc7186578edc1a9/index.d.ts#L54

https://github.com/implydata/plywood-druid-requester/blob/b1902d1554e2aafb4fb06450ce7f0450e96b6985/src/druidRequester.ts#L50

Druid request parameters are defined here:
https://github.com/allegro/turnilo/blob/dc49da491549117bfd92e31fe1d631c5266adaa6/src/server/utils/requester/requester.ts#L55

I hope it helps in the beginning of the secured Druid cluster journey :)

**Comment by elukey** [comment]
Thanks a lot!
