### ISSUE TITLE
12-hour clock or 24-hour clock time in line charts?

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#273]
In the floating tooltips of line charts, I get time ranges like `0-0:05am` and `23:55pm-0am`. These timestamps append am/pm to a 24-hour clock, so they don't follow the [12-hour clock](https://en.wikipedia.org/wiki/12-hour_clock) rules.

Do you think it's better to adhere to one of the standard time conventions (by removing the am/pm part, or minus 12 from the number of hours for >=13:00 and set 0am to 12am)?

**Comment by l2dy** [comment]
> Actually it's here: https://github.com/allegro/turnilo/blob/master/src/common/utils/time/time.ts#L30..L31
> 
> If we wan't 12-hour clock we need change capital "H" to lowercase "h". If we want 24-hour clock - remove "a".

Timestamps in the Table view are also affected, are they also from these two lines of code?

**Comment by adrianmroz** [comment]
No, table labels and x-axis on line chart have additional logic to format time, so they have own methods: https://github.com/allegro/turnilo/blob/master/src/client/visualizations/table/table.tsx#L57 and https://github.com/allegro/turnilo/blob/master/src/client/components/line-chart-axis/line-chart-axis.tsx#L39 respectively. They both use d3.time to format and I think this function doesn't respect timezone so it's tied to #274. We need to think about what should be displayed and then use one formatter - d3.time.format or moment.format.

**Comment by l2dy** [comment]
I think we can go for 24-hour clock first, then perhaps make it configurable from the client.

**Comment by l2dy** [comment]
> Since the milestone is set to 1.13, can we merge #276 first as a bugfix for `23pm`?

What do you think? @adrianmroz

**Comment by adrianmroz** [comment]
Our plan is to fix time/timezone/formatting issues in 1.13, so for me there's no value in merging it now if we override that in next release. Will it help you if we merge it now?

**Comment by mkuthan** [comment]
Let's merge this PR for 1.12 release, event if the datetime formatting will be changed in 1.13.

**Comment by l2dy** [comment]
Great. It would help people installing Turnilo from npm.

**Comment by l2dy** [comment]
The bug is fixed, and we have a plan in #288 for unified time formatting. I'm closing this issue.
