### ISSUE TITLE
Choose better formatter for ticks of line charts with short time spans around year's end

### ISSUE THREAD

**Issue by piter75** [allegro/turnilo#279]
Current implementation of time format picker for line chart tick labels does not pick the best formatter for short spans at a year boundary.

As an example with a time span of 2 days with a year boundary included (Dec 31 - Jan 1) the line chart is presented with 9 ticks every 6 hours and each of them displays only date.

Responsible code:
https://github.com/allegro/turnilo/blob/17010b8965514b1ab1f6d85318513446614f5778/src/client/components/line-chart-axis/line-chart-axis.tsx#L44

**Comment by adrianmroz** [comment]
Closed via #317
