### ISSUE TITLE
Droping (dimension) filter on split should add split and preserve filter

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#292]
Worth noting is that would cause to "copy" dimension. We will get new split but filter will be still in place. Should we add some visual indicator of that?

**Comment by mkuthan** [comment]
I like the idea, D&D should be possible between filters and splits. I don't think that special visual indicator is needed for this scenario. Dragged dimension and destination place should be presented like in case of dragging dimension from left panel.
