### ISSUE TITLE
Move visualization tooltip to the left when part of it becomes invisible

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#305]
Part of the tooltip is invisible if the mouse is too close to the right edge of the browser.

<img width="167" alt="turnilo-tooltip-right" src="https://user-images.githubusercontent.com/14329097/52099901-1d344900-25cd-11e9-8afd-8c6433faf41a.png">

**Comment by l2dy** [comment]
Is this fixed in the recent tooltip changes?

**Comment by adrianmroz** [comment]
I hope so!

**Comment by adrianmroz** [comment]
Closed via #434
