### ISSUE TITLE
Configurable theme support

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#32]
Default Turnilo orange theme is aligned to Allegro L&F guidelines. It would be nice to configure Turnilo with different colour scheme.

- Theme should be configured as single property with theme name in the configuration file. 
- All SCSS variables for given theme should be defined in separate file. 
- SCSS variables for theme must be documented. 
- Allegro orange theme must be default one
- Swiv/PIvot blue theme should be available out of the box second theme.

**Comment by beibm** [comment]
Here is a project for reference，[State-Driven Styling in JavaScript ](https://github.com/rofrischmann/fela)

**Comment by adrianmroz** [comment]
Done in #573
