### ISSUE TITLE
ISO format date?

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#326]
Before #317, dates are shown in the `YYYY-MM-DD` (also `%Y-%m-%d`) ISO format, but the PR changed that to `D.MM.YY`. Can we revert to the original format to avoid confusion?

**Comment by l2dy** [comment]
I'm OK with `14 Feb 0:00`, but `14.02 0:00` (line chart x-axis, commit 0b5e37cca8b44e0880ab4a2359379a38036674cb) is dangerously confusing.

**Comment by adrianmroz** [comment]
We can settle for #330 :)
