### ISSUE TITLE
Could not connect to Druid broker with HTTPS

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#337]
I tried to configure cluster.host as "druid-broker:443" but it does not work (Error: socket hang up).
As long as cluster.host is a http/https address I would expect the following configuration format where protocol is configured explicitly but port is optional:

http(s)://hostname[:port]/

Please keep the fallback to existing host:port format to avoid issue during Turnilo upgrade.

**Comment by l2dy** [comment]
Fixed since #346?
