### ISSUE TITLE
Better client error logging with Sentry

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#339]
Turnilo handles all client side errors and sends the errors to the backend where the errors are logged. So far so good. 

But without sourcemap the stack trace is not valuable at all. It would be nice to replace the custom error handling with Sentry, all the client errors could be reported directly to Sentry (Sentry supports sourcemaps and provides nice log aggregation and many more features).

If Sentry DSN is configured Turnilo could switch to reporting client errors directly to Sentry.

**Comment by adrianmroz** [comment]
What should happen to errors that are thrown before initialisation of Sentry client? Initialisation depends on `AppSettings` object which is async. Should we silently fail or report to backend? 

Btw. We should remove remove `qajax` dependency in https://github.com/allegro/turnilo/blob/master/src/client/utils/error-monitor/error-monitor.ts#L18
to reduce initial bundle size

**Comment by mkuthan** [comment]
So keep existing error handling as is. Sentry should be treated as optional and additional error handling method.

**Comment by adrianmroz** [comment]
Closed with #374
