### ISSUE TITLE
Variable in expression corresponding to the split granularity on time

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#352]
Imply has a [$MillisecondsInInterval](https://docs.imply.io/on-prem/visualize/measures#rates) variable that can be used to calculate the rate of a measure. Do we have a similar feature?

**Comment by adrianmroz** [comment]
I'm not aware of this. As I understand, this is some variable added to each plywood expression via `apply`.

**Comment by l2dy** [comment]
Feature request then ;) Can we add this or something similar to Turnilo?

**Comment by adrianmroz** [comment]
I would rather see that as some kind of expression on measure that you can set in UI. Like "percent of parent" this could be something like "rate of change". We need to sit down and discuss what use cases that could handle. If you have some examples in mind, please share. Let's keep this issue open for now.

**Comment by l2dy** [comment]
For example, having a count aggregation of HTTP requests, the QPS (queries/requests per second) measure can be used to estimate the load on web servers, while the count measure itself is still useful in other cases. https://en.wikipedia.org/wiki/Web_server#Load_limits

**Comment by l2dy** [comment]
> Example use case: having a count aggregation of HTTP requests, the QPS (queries/requests per second) measure (`$main.sum($count) / $MillisecondsInInterval * 1000`) can be used to estimate the load on web servers, while the count measure itself is still useful in other situations (e.g. analyzing damage of an incident). https://en.wikipedia.org/wiki/Web_server#Load_limits

I think making QPS (or other rate measures like bps) available as a measure would make it easier for beginners (users) to discover and use this feature. Implementing it in the UI is much more difficult than adding `$MillisecondsInInterval`, isn't it?

**Comment by adrianmroz** [comment]
Actually, I'm working right now on measure expressions in UI :) It's my priority now, so when I finish, we could assess what to do next. 

About adding this variable, I'm not so sure how to get that value from Druid.

**Comment by l2dy** [comment]
Ah, I misread your point. That's great news to hear.

**Comment by l2dy** [comment]
> About adding this variable, I'm not so sure how to get that value from Druid.

Doesn't `granularity` and `intervals` in the Druid query determine the interval Druid returns?

**Comment by l2dy** [comment]
> Actually, I'm working right now on measure expressions in UI :) It's my priority now, so when I finish, we could assess what to do next.

With measure expressions shipped in 1.15.0, what's the plan for this feature request?
