### ISSUE TITLE
Dimensions ending with a numeric string could be indistinguishable in line charts

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#354]
Dimension that ends with a numeric string is indistinguishable from numeric measures. For example, in the image below `e4` is the dimension, and `757.0` is the measure.

<img width="243" alt="turnilo-4" src="https://user-images.githubusercontent.com/14329097/53805202-674c7980-3f41-11e9-9313-aeab28745c40.png">

**Comment by adrianmroz** [comment]
We should add padding also on current value: 
https://github.com/allegro/turnilo/blob/master/src/client/components/color-swabs/color-swabs.scss#L35..L45
