### ISSUE TITLE
unable to configure rounding or decimal places shown

### ISSUE THREAD

**Issue by trtg** [allegro/turnilo#373]
I'm having an issue looking at metrics whose aggregated value requires more than 1 decimal place. For example I was debugging a set of 12 events each of whose value was 0.015 so the sum of the 12 events was 0.18. Turnilo shows the value of the individual events as simply 0 and the sum of all the events as 0.2. Both of these issues (too few decimal places, and undesired rounding) are not ok for us. Is there any way to adjust both of these things through the config.yaml or elsewhere?

**Comment by adrianmroz** [comment]
You can set default format for measure in configuration (format field in https://github.com/allegro/turnilo/blob/master/docs/configuration.md#measures) or user can select desired format for measure in measure menu (even define their own number format like in configuration).

**Comment by trtg** [comment]
Thanks for the reply @adrianmroz I was able to follow the docs and define a format in the config.yaml and I just realized that the selected measures are clickable in the UI in order to configure them. I was confused because the way to do this in pivot is quite a bit different. Thanks again.
