### ISSUE TITLE
Union query with multiple data sources

### ISSUE THREAD

**Issue by alexbusu** [allegro/turnilo#375]
Any plans to add this feature, please?

**Comment by adrianmroz** [comment]
We don’t have plans for it, but because we don’t have use case for it yet. Convince us :)

I read something about unions in druid but I’m not sure how it fits into Turnilo idea. Feel free to elaborate how you imagine this feature.

**Comment by alexbusu** [comment]
In theory it sounds simple. A new feature that may be called "Union data source". 
To configure, one must select the data sources for the new union (from available data sources list). The Union data source can appear in list as the other ones.
In visualization window, the dimensions and metrics are a list on distinct items from the merge of both data source's dimensions and metrics.
The query for this "Union data source" will be changed from 
```
{
  "dataSource": "sample-data-source"
}
``` 
to
```
{
  "dataSource": {
    "type": "union",
    "dataSources": [
      "redirects",
      "sales"
    ]
  }, ...
}
``` (where redirects and sales are almost identical druid data sources looking at dimensions list, with different metrics only).

**Comment by adrianmroz** [comment]
Oh, so you just want to give ability to define that in configuration yaml and hide from user? That really sounds quite simple.

**Comment by mkuthan** [comment]
Quick look into plywood and I found support for union but it needs to be verified:
https://github.com/implydata/plywood/blob/3e2bbfe71720ac988411998932b5c5f58464350b/src/external/druidExternal.ts#L480

We'll take a look but I can't give you exact date.

**Comment by alexbusu** [comment]
Thanks for the hint, @mkuthan 
Following the link you posted I noticed that plywood expects data source to be string or array of strings, so I tried with array of strings in config file, no dimensions or metrics definitions, and it seems to work already.
![image](https://user-images.githubusercontent.com/4104165/56194485-02e60500-602b-11e9-97d0-17af29e20846.png)
This is the `dataCube` config:
```
- name: clicks-sales
  title: clicks-sales
  clusterName: druid
  source: [ 'clicks', 'sales' ]
  refreshRule:
    rule: query
  introspection: autofill-all
```
and can be the only one defined, or together with `clicks` and `sales` and/or other cubes as well; it will work.
At some point I got some issues, like listing the metric in Metrics list but after adding in series tile an error is thrown ("column not recognized" kind of error). But I cannot reproduce this already. All looks good now :)
Cheers!

**Comment by adrianmroz** [comment]
I wouldn't close it so fast, right now source is defined in our models as string so we lose some information.

https://github.com/allegro/turnilo/blob/master/src/common/models/data-cube/data-cube.ts#L83

Let's leave it open so we could sort out our models.

**Comment by mkuthan** [comment]
It also should be documented in the "Configuring Data Cubes" section.

**Comment by javaHelper** [comment]
@adrianmroz - Could you please guide here: https://stackoverflow.com/questions/62510899/spring-batch-create-two-datasources-and-how-to-customized-to-use-other-propert?
