### ISSUE TITLE
Blank UI once connected to druid broker?

### ISSUE THREAD

**Issue by DanoOM** [allegro/turnilo#386]
I did the install following the instructions..as in:
`[centos@uswest2-dev-turnilo-001 ~]$ nvm install 10.0.0
Downloading and installing node v10.0.0...
Downloading https://nodejs.org/dist/v10.0.0/node-v10.0.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v10.0.0 (npm v5.6.0)
Creating default alias: default -> 10.0.0 (-> v10.0.0)
[centos@uswest2-dev-turnilo-001 ~]$ nvm install 10.0.0^C
[centos@uswest2-dev-turnilo-001 ~]$ npm install -g npm@6.5
/home/centos/.nvm/versions/node/v10.0.0/bin/npm -> /home/centos/.nvm/versions/node/v10.0.0/lib/node_modules/npm/bin/npm-cli.js
/home/centos/.nvm/versions/node/v10.0.0/bin/npx -> /home/centos/.nvm/versions/node/v10.0.0/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.5.0
added 275 packages, removed 362 packages and updated 49 packages in 6.3s
[centos@uswest2-dev-turnilo-001 ~]$ npm -v
6.5.0
[centos@uswest2-dev-turnilo-001 ~]$ node -v`

if I startup with: 
turnilo --examples
UI comes up as expected :)

if I startup with my our broker (we only have 1 atm)
then I goto the UI, I get a blank page.
now..
on back on the server I see:

`Starting Turnilo v1.14.0
Turnilo is listening on address :: port 9090
Adding cluster manager for 'druid' with 0 dataCubes
Connected to cluster 'druid'
Cluster 'druid' is running druid@0.14.0-incubating-iap3
Introspecting all sources in cluster 'druid'
Scanning cluster 'druid' for new sources
Cluster 'druid' making external for 'messages_detail'
Got queryable external dataset update for messages_detail in cluster druid
Got the latest time for 'messages_detail' (2019-01-31T23:59:59.000Z)
Got the latest time for 'messages_detail' (2019-01-31T23:59:59.000Z)
Got the latest time for 'messages_detail' (2019-01-31T23:59:59.000Z)
Got the latest time for 'messages_detail' (2019-01-31T23:59:59.000Z)
`
So I'm guessing it walking segements or some such?
if yes..wouldn't the time stamp be changing or?

If there is forum/better place to 'discuss' this, please point me in the right direction.
thanks

**Comment by adrianmroz** [comment]
Please join our micro community on slack if you prefer, https://join.slack.com/t/turnilo/shared_invite/enQtNDk5NTkzNTkzMjgzLTc1MTg5MzFjNTBjYmQ4MmUyN2RlNjNmZWE0ODZmZWNjYzZlY2YyYWY2YjQ0Y2Y1ZmNiZjc5NDY3ZjRhM2U4Y2M

Turnilo queries druid for latest time available and does it in intervals. If there's no new data, the time will be the same.

You can add "--verbose" flag for more logs.

**Comment by DanoOM** [comment]
the blank screen, it shows very briefly, the orange dots, then screen goes white, the browser console, shows:
main.js?v=1.14.0:14 TypeError: Cannot read property 'title' of undefined
    at Function.e.firstMeasure (app.7e094fdf734a95564ed7.js:37)
    at app.7e094fdf734a95564ed7.js:21
    at Object.visualizationIndependentEvaluator (app.7e094fdf734a95564ed7.js:21)
    at r (app.7e094fdf734a95564ed7.js:1)
    at new n (app.7e094fdf734a95564ed7.js:1)
    at Function.n.fromDataCube (app.7e094fdf734a95564ed7.js:1)
    at n.getEssenceFromDataCube (app.7e094fdf734a95564ed7.js:37)
    at n.updateEssenceFromHashOrDataCube (app.7e094fdf734a95564ed7.js:37)
    at n.componentWillMount (app.7e094fdf734a95564ed7.js:37)
    at mountClassInstance (main.js?v=1.14.0:14)

stack shows up 3 times:
from main.js: line 14
from main.js: line 1
from app....js: line 37

**Comment by adrianmroz** [comment]
See #408 for future reference
