### ISSUE TITLE
NavLogo in SideDrawer

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#392]
We removed NavLogo from side drawer to have more vertical space and simplify user interactions with "modal" UI. 

But as @alexbusu said:

> It's a documented and functional component (just to remove onClick={onClose}, or to onClose={onClose}).

So maybe keep it non interactive (closing when clicking on logo was not intuitive) and hidden by default? If `customLogoSvg` is set, show logo, if not - don't show default, just omit.

Thoughts?

**Comment by alexbusu** [comment]
Hidden by default, with option to enable sounds great.
