### ISSUE TITLE
Display Druid Query causes crash in case of using custom aggregations (post-aggregations)

### ISSUE THREAD

**Issue by alexbusu** [allegro/turnilo#393]
![image](https://user-images.githubusercontent.com/4104165/56655928-07926500-668c-11e9-8fdd-d4cbb27893bc.png)
It seems there is data missing on client side, when trying to build the query.

**Comment by adrianmroz** [comment]
Oh my, I'm really confused. 

Do you configured Sentry for your turnilo instance? If so, that's code of error in your sentry instance, so you need to share here more information from sentry.

If not - that's confusing part. Does sentry client assigns ids without proper DSN?

**Comment by adrianmroz** [comment]
Ok, I checked, sentry still generates ids without proper configuration.

**Comment by alexbusu** [comment]
No Sentry configured. 
The issue is due to missing `dataCube.options.customAggregations` in client's `__CONFIG__`.
Also, passing `customAggregations` to plywood's `External` (query) is required, in `DruidQueryModal`.

**Comment by adrianmroz** [comment]
Yup! Nevertheless I should sort out this Sentry initialisation ...
