### ISSUE TITLE
Handle error reporting without sentry

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#395]
When sentry is not initialised, it's methods still behave as it was. So for example `reportError` generates `errorId` and we present it to the user. 

What is desired behaviour? We should log error to the console? It's client side error so there should be no sensitive data but printing that on the screen would be bad UX. 

via #393

**Comment by mkuthan** [comment]
It should be basic fallback for client side error handling if sentry configuration is missing. I think that logging into console would be fine.

**Comment by adrianmroz** [comment]
> It should be basic fallback for client side error handling if sentry configuration is missing. I think that logging into console would be fine.

9aef724

**Comment by adrianmroz** [comment]
Closed via #396
