### ISSUE TITLE
Can't remove the datacube for deleted datasource

### ISSUE THREAD

**Issue by likunbyl** [allegro/turnilo#398]
Hi, everyone, I have deleted data source from druid, but I can't find a way to remove the datacube for this data source in the turnilo. How can I clear useless datacubes ?

**Comment by adrianmroz** [comment]
Only via turnilo reset.

**Comment by likunbyl** [comment]
Restart turnilo, right? or can I send it a signal by kill?

**Comment by adrianmroz** [comment]
Yes, turnilo. SIGTERM will kill it, but you need to start it again.

**Comment by likunbyl** [comment]
ok, thanks.
