### ISSUE TITLE
Enhancement suggestion: Scheduling reports to my email.

### ISSUE THREAD

**Issue by mihirtech** [allegro/turnilo#402]

**Comment by mihirtech** [comment]
Can I schedule mailers that would send the data reports on regular intervals (daily/weekly) to my email id. As a user, I should be able to 1. Select data points (Dimensions/Metrics/Duration), 2. Mailer frequency, 3. Email ID. I should get a mail with a CSV attached and the URL.

**Comment by mkuthan** [comment]
@mihirtech Turnilo is a data exploration tool, not a scheduler. But you could use scheduler of your choice (e.g cron, apache airflow), generate links to any given report programatically and send the any notification you need with the generated link:
https://github.com/allegro/turnilo/blob/master/docs/generating-links.md

What do you think?

**Comment by adrianmroz** [comment]
Close due to inactivity.
