### ISSUE TITLE
Enhancement: Link display values between multiple charts

### ISSUE THREAD

**Issue by alexbusu** [allegro/turnilo#403]
It would be helpful to display all charts value at some point in time when mouse-move over a single chart. As an example, [have a look here](http://www.tylernwolf.com/legacy/#/portfolio/corrdisp).
Following the screenshot from the actual line charts view: 
![image](https://user-images.githubusercontent.com/4104165/56905902-11a3d180-6a99-11e9-9617-763b9549d593.png)
an idea would be display `hoverInfo` for all charts instead of single one. Also an extra vertical line could be added (between chart graphics and hover info) if not much work to do (I guess a charts wrapper would be required).

**Comment by mkuthan** [comment]
It could be useful, thanks for the enhancement proposal. I don't know when we put this enhancement to our roadmap, but feel free to create PR :)

**Comment by adrianmroz** [comment]
Do we want to connect lines between charts though? Spacing between charts is quite small, so gaps in line between charts wouldn't be a problem for user perception. And we don't need to solve problem when line crosses total label on the left.
