### ISSUE TITLE
--with-comments option breaks config file

### ISSUE THREAD

**Issue by elisae** [allegro/turnilo#405]
## Issue
When dumping a config file with comments (`--print-config --with-comments`) the resulting config file cannot be parsed:
```
$ turnilo --druid http://localhost:8082 --print-config > config.yaml
$ turnilo --config config.yaml
Could not load config from 'config.yaml': bad indentation of a mapping entry at line 17, column 7:
          sources added as data cubes. Def ...
          ^
```
## Reason
The config.yaml contains multiline comments of which only the first line is preceeded by a `#`:
<img width="973" alt="Screen Shot 2019-05-03 at 14 34 52" src="https://user-images.githubusercontent.com/9415550/57137634-baf80980-6db0-11e9-8448-1d138c7df571.png">

## Solution
Fix file generation somewhere :)

**Comment by adrianmroz** [comment]
Oh, problem is with https://github.com/allegro/turnilo/blob/master/src/common/models/labels.ts

We use template strings and they preserve new lines, so comments span multiple lines with just one hash.
