### ISSUE TITLE
Having clause and filterable metrics

### ISSUE THREAD

**Issue by pguzik** [allegro/turnilo#41]
It would be lovely if we could add a feature similar to Having clause. For example I would like to filter metric values only for people who bought at least 10 items. Or to see values for people who spent money in range (range filtering).

From the UI perspective it would be nice to add filter option for metrics (numerical values). Metrics should be filterable.

**Comment by mkuthan** [comment]
Metrics could be filterable exactly as numerical dimensions. But metrics in the filter box must have strong visual indicator to distinguish dimension and metric filters. Different box colour?

**Comment by mkuthan** [comment]
Umbrella issue: #184

**Comment by adrianmroz** [comment]
Filterring should be available for all measures (but not virtual measures like measure expressions) on every visualisation.

**Comment by adrianmroz** [comment]
FilterMenu as NumberFilterMenu. At start fetch should get min and max of measure value with currently applied filters.

**Comment by mkuthan** [comment]
Filters on aggregated metrics make sense only for groupBy queries. Filtering for topN queries are fixed by query definition (always top N), so as long as Turnilo spawns topN queries instead of groupBy there is no way to provide sql having functionality.
