### ISSUE TITLE
Add animation effect for vis (line, bar...)

### ISSUE THREAD

**Issue by beibm** [allegro/turnilo#411]
Any plans to add this feature？

**Comment by adrianmroz** [comment]
We don't have anything about this in the pipeline. Do you have any specific requests? On visualisations we often change whole chart (for example acting changing filter/split) so animating that could look really bad with a lot of bars/lines morphing into something different. Maybe something after auto refresh in realtime sources? I'm not sure.

**Comment by mkuthan** [comment]
.02$ from my side - animations are very good if you want to sell the product - but if you need a daily basis tool to make your job done ... ;)
