### ISSUE TITLE
Time comparison on table, chart and bar visualisations

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#43]
- It should allow to compare the same time period in the past
- Only for single split based on time
- Selected on time split modal
- Compared to the same period of time in the past
- On the chart and bar views second time series should be presented as a dashed line and the percentage on the tooltip
- On table view two additional columns should be presented (metric for the compared time period and percentage)
- Single query to the Druid cluster for both time ranges if feasible in plywood
- Comparison must be bookmarkable, it also means that mkurl must handle this kind of visualisation properly.

**Comment by on99** [comment]
This is a great feature included in superset, is it hard to implement in turnilo? @mkuthan
