### ISSUE TITLE
Broken layout for multi-(line-)chart series

### ISSUE THREAD

**Issue by alexbusu** [allegro/turnilo#433]
Following the https://github.com/allegro/turnilo/pull/428 some layout issues arised.

* The tooltip position is too far from mouse position:
![image](https://user-images.githubusercontent.com/4104165/58405057-7cc3d200-805e-11e9-91aa-e37c07be942c.png)

* On the left edge the tooltip doesn't switch position relative to mouse, and gets hidden.
![image](https://user-images.githubusercontent.com/4104165/58405083-89482a80-805e-11e9-9c35-5b28b88a6f1b.png)

* Selecting 3 measures or more will break tooltip style and vertical position.
![image](https://user-images.githubusercontent.com/4104165/58405108-97964680-805e-11e9-945d-6fed8fde3312.png)

Spotted using Google Chrome (latest). (On Ubuntu 18.04, if it matters)

Thank you!

**Comment by adrianmroz** [comment]
Ok, I see those issues on my end. Let me fix 'em :)

**Comment by adrianmroz** [comment]
Issue is with left panel. When it's open, positioning of tooltip breaks - TooltipWithBounds is not aware of that left panel or somehow, it takes into account double of left panel width?

**Comment by adrianmroz** [comment]
#434 fixes most of it, but still vs/tooltip can position itself weirdly in small resolutions. OTOH turnilo doesn't work great in small resolutions ...

**Comment by alexbusu** [comment]
It looks great now; awesome, thanks!
