### ISSUE TITLE
Put selected values on top in the filter menu

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#439]
1.16.0-beta.0:
<img width="496" alt="beta" src="https://user-images.githubusercontent.com/14329097/58928421-ef5d3d80-8741-11e9-84cf-28dcc607f0f2.png">

1.15.0:
<img width="267" alt="stable" src="https://user-images.githubusercontent.com/14329097/58928432-f6844b80-8741-11e9-8201-2262f0b68172.png">

**Comment by l2dy** [comment]
This is reproduced by selecting some values, clicking OK, and then open this menu again.

**Comment by mkuthan** [comment]
A few comments:
* For include/exclude the selected values should be presented at the top of the list. The remaining elements should be sorted by cardinality.
* When the filter is changed, input from "contains" should not be automatically assigned as input for "regex", the input from "regex" should not be automatically assigned as input for "contains". "Contains" and "Regex" expressions differ from each other.
* In general, switching between filter types ("include/contains/regexp) should clear search input field. The only exception is when the include is changed to exclude or exclude to include - selected values should be kept.
