### ISSUE TITLE
Overlapping line chart hover indicators

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#445]
<img width="813" alt="overlap" src="https://user-images.githubusercontent.com/14329097/59368617-2b8a3280-8d2e-11e9-9781-c03b3231d9e9.png">

hover indicators of "Avg Added" and "Deleted" overlapped, captured from Turnilo aa0bfcb8ab5d59366dbfd0b95ddc32a8f192a901

**Comment by adrianmroz** [comment]
I reproduced this when space for last tooltip is very small (lot of measures, low height of visualisation). It is issue with our usage of `vx/tooltip`. Thanks for report but this could take some time to resolve. Don't hold your breath :)

**Comment by l2dy** [comment]
Fixed in 1.25.0? @adrianmroz

**Comment by adrianmroz** [comment]
We increased minimal chart height a little, so it is harder to find overlapping case but it's still possible.

**Comment by l2dy** [comment]
<img width="1327" alt="Screen Shot 2020-05" src="https://user-images.githubusercontent.com/14329097/82420042-c8625d80-9ab1-11ea-863a-a25c31776e38.png">

There is only one hover box now, so it can't overlap anymore ;)

**Comment by adrianmroz** [comment]
You're right! I shouldn't respond to notifications before morning coffee!
