### ISSUE TITLE
Time Shift not working for Table split by TIME

### ISSUE THREAD

**Issue by dataedgehungary** [allegro/turnilo#446]
Hi All,

Maybe I am doing something wrong, but Time Shift is not working if I want to group (split by) for any period... day/week/month nothing. (image attached)

Same for the line chart, if I apply any Time Shift, the line disappears.

![turnilo_table_time_split](https://user-images.githubusercontent.com/41633732/59494933-8a66bd80-8e8e-11e9-9ff5-260d54d091da.JPG)

**Comment by adrianmroz** [comment]
Is it also failing for less extreme time periods? Let's say last day with time shift one week? 

I assume you are using turnilo 1.16 and connect it to druid broker? 
Do you have data for desired periods? If you just filter for defined periods, does turnilo show correct data?

**Comment by dataedgehungary** [comment]
Thanks for the reply, yes the same thing happens with less extreme values. I attached the picture. If I remove the split by time, then the values are correct for the Time Shift.

Turnilo 1.16 with druid broker yes.

![shift_2](https://user-images.githubusercontent.com/41633732/59501808-99ed0300-8e9c-11e9-99fb-63185fc40d9c.JPG)

**Comment by adrianmroz** [comment]
Ok, so I see two problems there:

You don't have Previous Brutto for 25-31 May and from UI it looks that you miss those values in Druid. Is it true?

You have `null` on time dimension and I'm not sure what could lead to this.

**Comment by dataedgehungary** [comment]
No it is not true, I do not have missing values. I attached the screen, without the timeshift for the entire dataset. There are no null time values. It is a transactional basket value log from a supermarket POS. Also, the Previous Brutto values on the second screenshot are not correct. For some reason It takes the current value as previous for those days from 2nd till 24th of May.

Again, if i remove the SPLIT, then the Previous Values are correct (attached).

![shift_3](https://user-images.githubusercontent.com/41633732/59504672-bc364f00-8ea3-11e9-877a-c38b0d372a5a.JPG)


![shift_4](https://user-images.githubusercontent.com/41633732/59504677-bfc9d600-8ea3-11e9-9ab3-e1d1d942a0fd.JPG)

**Comment by mkuthan** [comment]
I'm not able to reproduce this situation for exactly the same filter and split on datasource with daily granularity and 3 years of retention. Current, previous and diff are calculated correctly.

Could you check again your datasource, especially the reason of "null" bucket on time dimension? What is a datasource granularity for current and previous year segments?
