### ISSUE TITLE
Time shift not correctly applied in line chart view

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#449]
e.g. last 6 hours with 1 hour shift:

![Screenshot_2019-06-22](https://user-images.githubusercontent.com/14329097/59961331-b8b74f00-94c5-11e9-8fef-9ab36ba118a0.png)

[reproduce link](http://127.0.0.1:9090/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5VIazBrosuAuZEA2ABKSo8pr4pACMTBra3AjoxAEgAL4AuklMUJpIaHYOETrMEGyS1vnE2FBuJsWSAOYu2DDRNBAa3J4ArACy/ph0+KCGxrqV4Vq5RWyl5UxFhuQYONxwUOQlRdhVCUxILE34dQgIKSBQVrEqfUYKJcsL1tbE1pJS3Szovcwj3HdScPX0TGCIGC5DbvSIENiLZxcQ6aCDYEjWAAixQmOCyICocHhxAQkmwcDYaTg1yY0AASpgAEaYeiJJiw7HWADK3XoBDgt3uZmKTMoECkbJAnhCfk2xCqK129QQTD5VUoSHlbL2ByAA===)

**Comment by l2dy** [comment]
The solid line proves that at Sep 12 23:00 there is data available, but the dotted line stops at 22:00 (an hour shifted, so 23:00 in the X-axis label).

**Comment by adrianmroz** [comment]
You can see the issue also on [table viz](http://127.0.0.1:9090/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhpwBGCApiADSEQC2ZyOFBAomgMYD0AqgCoDCVEADMICNGQBOUfAG1QaAJ4AHZjXpDJZYfnUVqGegAUpWACYy88kGZiT0WXASO8AbAAkhUCcvwBaAEYDFTUEdDJvEABfAF1Y6ihlJDRLayVVXUN9GzoybChHTNyhAHN7bBgwyQglXRcAVgBZL0xJNHxQLR0CLKF0tTNc/MLqQa12DBxdOCh2PMHsEujqJFoa/AqEBHiQKFMIuU7tKTy56bMzMjMhYVbadA7CEN1L4ThK9uowRBg1ZaeMgR6DM7BQdsoINhsFcACJDAo4VIgdgACzgULICCE2Dg9EScDO1GgACVMMRMO0YtQIRizABlVrtAhwC5XPq5OkoiDCJkgFwBTwrMgleYbSoIahckoopDSpmbbZAA=)

It is result of overlapping periods. It would be very hard to fix from technical pov. Maybe we should discuss if it should be even possible to select?

**Comment by adrianmroz** [comment]
> Maybe we should discuss if it should be even possible to select?

We should disable such selections
