### ISSUE TITLE
Is there a way to match specific dimensions to specific measures?

### ISSUE THREAD

**Issue by thomaslu3** [allegro/turnilo#450]
In Turnilo is there a way to match specific dimensions to specific measures? For example, if I have a measure for “average_latency,” is there a way to have the dimension “computer_name “ only for that measure? Meaning that if there were another measure, let’s say “error,” you wouldn’t be able to use the dimension “computer_name” with error?

**Comment by adrianmroz** [comment]
No, turnilo doesn't allow that. Under the hood turnilo assumes that datasource is kind of data cube (or some other olap lingo), so such feature had to be done on presentation layer alone. That makes it very unlikely.
