### ISSUE TITLE
A little scrollbar is displayed near every measure on the list

### ISSUE THREAD

**Issue by grzaks** [allegro/turnilo#456]
The CSS `display: flex` (or the fixed `height: 24px`) of `.measure-item` makes tiny scrollbar appear near every measure on the list. See screenshot attached.

Disabling either of these CSS rules in the browsers webdeveloper tools fixes this, but the row height is 27px then, not 24px.

![turnilo01](https://user-images.githubusercontent.com/6290066/61062339-597e9780-a3fe-11e9-9c09-16098c19dd9f.png)

**Comment by adrianmroz** [comment]
Duplicate #443 

Thanks for reporting!
