### ISSUE TITLE
quantilesDoublesSketch support

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#458]
According to [Druid docs](https://druid.apache.org/docs/latest/development/extensions-core/approximate-histograms.html), the Approximate Histogram aggregator is deprecated.

`quantilesDoublesSketch` support was introduced in Plywood 0.20.8, so it should be easy to add to Turnilo.

**Comment by l2dy** [comment]
BTW, related Plywood commit is https://github.com/implydata/plywood/commit/2a973eae50e1cc53c3329d18a197aa5520b1e18e.

**Comment by mkuthan** [comment]
We are going to test DataSketches quantiles as well, so I assigned this issue to 1.17 milestone. Thanks for reporting and checking Plywood capabilities!
