### ISSUE TITLE
Contextmenu doesn't handle items inside on smaller viewport

### ISSUE THREAD

**Issue by Radwojt** [allegro/turnilo#492]
Just noticed that contextmenu of filters doesn't handle items inside on smaller viewport (when height is  < 560px.
![image](https://user-images.githubusercontent.com/10118160/67468022-0f868e00-f64a-11e9-865a-f20de19b885a.png)

Will fix it immediately :)

**Comment by adrianmroz** [comment]
There are few bugs like that, but they're low on our priority list. We could use your help!

**Comment by adrianmroz** [comment]
![image](https://user-images.githubusercontent.com/14370131/67568462-96139c00-f72c-11e9-8619-57244392f436.png)

BubbleMenu overflows opened Dropdown inside
