### ISSUE TITLE
Legend color mismatch if split is sorted by difference in line chart

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#494]
<img width="1275" alt="turnilo-legend" src="https://user-images.githubusercontent.com/14329097/67544840-99f1ef00-f729-11e9-87ea-9a6f96deb66a.png">

Reproduce link: http://127.0.0.1:9090/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5VIazBrosuAuZEBGAEwAJSSh5TXxSLyYNbW4EdGIgkABfAF1kpihNJDQ7B0idECCaCGwAc0lrCDZsKDduKjhsEgRAzDp8UENjAjhra2JrMy08qCs4sohDcgwcbl6ocmJscpLJbULMfoIAfV65OE3NxKYkFgh6PGwYBAQEhjVBkwr9R0eqmt1HyWKXC5jCjW5PF4AmkWmd2kYHmwBlECOVKtVpkxyhMpu4QHA5gslqUboQKqd8D9rkk0iNsuCpAoFvNuN1ev0mFIWix0G1mPdYUY4Jd6EwwIgYHlDuyYSA2BjnFxUiBNEUSNYACIvBFVFQgaAAJUwACNMPQSTK5X0AMqg2k9PpmR7GygQKRnECA/ySBDEYpYtlwhYq2rUBrEJpHfFnACsfIFo3OlwQTGoUAActH8FJEMNcbbipQkJmzkSEkA=

**Comment by adrianmroz** [comment]
This need to wait on #399 

Issue is:
Pinboard doesn't accept Periods of main Series as valid Sort fields. It shouldn't.
Problem is, Legend uses same component and there are inconsistencies. We need to split those components and Legend component need to be aware of periods and thus show correct colours.

**Comment by adrianmroz** [comment]
Closed by #562

**Comment by l2dy** [comment]
> This need to wait on #399

Is it fixed in #595? What's the status of #399?

**Comment by adrianmroz** [comment]
As far as I can tell, it's fixed. Reopen if you think otherwise.

**Comment by l2dy** [comment]
The sorting drop-down menu in the legend component is removed in 1.24. Is this intentional?

**Comment by adrianmroz** [comment]
Yes. Data is presented as is in line chart so they share sort settings. More consistent.
