### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by felixmw** [allegro/turnilo#500]
Dear all, I have some questions regarding the formatting of numbers in Turnilo.

1) How do I make Turnilo/Numbro apply "European/German" formatting of numbers, e.g. using "€" as the currency symbol and use "," as the decimal seperator and "." as the thousandts seperator?

2) Is there a way to align numbers at the decimal seperator?

Your help is highly appreciated,
thanks a lot,
best
Felix

**Comment by adrianmroz** [comment]
I need access to computer for that. Let me come back to you at monday.

**Comment by felixmw** [comment]
Thanks a lot for your instant reply. Looking forward to your solution.

Best
Felix

**Comment by adrianmroz** [comment]
> 1. How do I make Turnilo/Numbro apply "European/German" formatting of numbers, e.g. using "€" as the currency symbol and use "," as the decimal seperator and "." as the thousandts seperator?

This is not possible right now. By default numbro uses en-US locale. It would be worth to create issue and check if we could add locale selection to configuration. That could solve delimiters and currency symbols.

> 2. Is there a way to align numbers at the decimal seperator?

Nope. Only way is to enforce number of decimal digits (`[0.00]` for two digits).

**Comment by felixmw** [comment]
Hi @adrianmroz and thanks for your feedback on this one. I opend a separate issue on the locale in numbro (https://github.com/allegro/turnilo/issues/504#issue-517301948).

Best
Felix
