### ISSUE TITLE
serverRoot configuration option is not respected for fonts and favicon paths

### ISSUE THREAD

**Issue by magor** [allegro/turnilo#509]
We run multiple instances of turnilo behind proxy with authorization module divided by path prefix (with one of them on /; we use this to allow different groups of users to access different sources). But instance with non-empty prefix (ie. domain.net/prefix/, serverRoot="prefix") tries to download fonts and favicon from url without said prefix (ie. domain.net/favicon/...). I assume the right url would be domain.net/prefix/favicon/.

**Comment by adrianmroz** [comment]
Few things there:

- [ ] requests for statics should be relative

- [ ] we should add `serverRoot` prefix to statics router

- [ ] we should serve routes only on `serverRoot`, not on root and prefix

- [ ] we should change default for `serverRoot` and ensure it works for routers
