### ISSUE TITLE
Pivot table but with just columns a.k.a grid

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#539]
First, we need better name for this visualisation!

So we'd like to implement visualisation like current table, but instead of nesting splits and showing sub-totals, we would add one column per split. 

So for view definition: splits: User Id, User Name, Age and series: Clicks, Visits we would get something like:

User Id | User Name | Age | Clicks | Visits
------------ | ------------- | ------------- | ------------- | -------------
1 | Adrian | 6 | 421 | 32
2 | John | 26 | 31 | 2
3 | Joe | 62 | 31231 | 111
4 | Bob | 16 | 231 | 2

If you provide split that yields more than one value, we will repeat row with until that difference :

User Id | User Name | Year | Clicks | Visits
------------ | ------------- | ------------- | ------------- | -------------
1 | Adrian | 2019 | 21 | 2
1 | Adrian | 2018 | 321 | 1
2 | John | 2019 | 31 | 2

Time shift will be handled just like on Table right now - with additional columns.

Feedback? @cedrics @l2dy @alexbusu @mkuthan

**Comment by luckey01** [comment]
Is this a proposal for an additional visualisation? or a change to the current visualisation?

If the latter, while understanding its a trade off, a couple of objections.

I see the advantage if your splits often yeild 1 value. But the nesting is great for us for 2 reasons

1 - the subtotals. our splits often have many more than 1 value, so having these subtotal provides alot of advantage, that isn't so clear from the examples in the description.
2 - The values of our dimensions _sometimes_ have long names, so in your example above, if I made the values of User_id and User name long (i know this is garbage) it still looks like:

| User Id                                     | User Name                                                   | Age | Clicks | Visits |
|---------------------------------------------|-------------------------------------------------------------|-----|--------|--------|
| 1853489534942387947893278932459825349432897 | Adrianfdsgsdkjlfsnhjklsgfnkjhflgknjfsdlfmngkjhfsklfdsgdf    | 6   | 421    | 32     |
| 243843595473899283987423892438793478942798  | Johnfdasgfdsfdhjsakfbdjklnfjdkshzgflkjsdnfjsdhuijlkfngsjsfd | 26  | 31     | 2      |
| 345378982978493974238974879437984982398742  | Joefdsagfdjkshxvnmzhfergiuhdfnknbkdfhsgjkrhejfdnzxkghklhsu  | 62  | 31231  | 111    |

Which pushes the values of clicks and visits out of the screen, and can be hard to see which User Id it matches up with. Nesting however has (most) of the user name directly under the user ID)

I see the advantage of dropping the nesting (also vertical information density), and understand its a tradeoff, it just wouldn't be so great for us.

**Comment by adrianmroz** [comment]
It will be additional viz. Current table stays.

**Comment by alexbusu** [comment]
That sounds interesting. As I see, now there will result one groupBy query instead of a topN cascade. Sure, why not :)
As for the name... "Compact table", "Grid", whatever.

**Comment by wmeler** [comment]
how about "flat table" ?

**Comment by mkuthan** [comment]
> That sounds interesting. As I see, now there will result one groupBy query instead of a topN cascade. Sure, why not :)

As I remember we tried to use groupBy query on existing table visualisation. And we failed, instead hundreds topN queries we got ... hundreds groupBy queries :(

But for sure, we should use regular groupBy query for the new excel-table like visualisation.

**Comment by mkuthan** [comment]
> First, we need better name for this visualisation!

Better name and icon :) 

We could get some inspiration from Excel (or maybe not?), in Excel this is a Pivot table with different report layout
