### ISSUE TITLE
costom default timezone makes wrong data

### ISSUE THREAD

**Issue by holiday12138** [allegro/turnilo#554]
when set default timezone of a datacube to hong_kong  in config.yaml and spilt time with day
 get empty data
![image](https://user-images.githubusercontent.com/19567508/72587274-a011f900-392f-11ea-8b53-69acbafb9322.png)
![image](https://user-images.githubusercontent.com/19567508/72587463-537aed80-3930-11ea-8901-bbfe403758c4.png)
![image](https://user-images.githubusercontent.com/19567508/72587483-5fff4600-3930-11ea-951c-bcd4f8086076.png)

ps: if choose heatmap,here goes 
![image](https://user-images.githubusercontent.com/19567508/72587619-b2d8fd80-3930-11ea-960f-1310dca6d459.png)

if I change the timezone param of route plywood to 'etc/utc' 
![image](https://user-images.githubusercontent.com/19567508/72587348-e7988500-392f-11ea-872d-8077048e5e52.png)
![image](https://user-images.githubusercontent.com/19567508/72587736-16632b00-3931-11ea-9fb7-96690ff07564.png)

can get real data
How to deal with it ?

**Comment by adrianmroz** [comment]
I couldn't reproduce this issue. 

Does it happen only on heatmap? 
Does it happen on specific date or all?

You could set default timezone in config-examples.yml and run turnilo with `--examples` option. That would load wiki dataset and you could confirm if it depends on your data. If I run example dataset, default timezone works nicely.

Lastly, in upper right corner you can select "Display Druid Query" and try to hit druid broker directly. Check if query looks good and what it returns.

**Comment by holiday12138** [comment]
it happend not only heatmap
and for almost all date
 I will try to check our cluster
