### ISSUE TITLE
Simplify Colors/Legend

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#562]
1. Remove "colors" from essence and view definition. "colors" key is now ignored in hash url converters.
2. On line chart, legend is read only. We show list of values and assign colors. To change visible values user need to manipulate explicitly splits limit and filter values.
3. Because we have 10 colors, right now we enforce limit 10 on line chart second split. (later we can decide in decoupled reolution functionality #472)
4. Remove search and sort (it is sorted the same as second split) functionality

**Comment by adrianmroz** [comment]
Closes #494 #387

**Comment by l2dy** [comment]
> Because we have 10 colors, right now we enforce limit 10 on line chart second split.

The default limit after adding a new split is "None" in 1.24.0-beta.0, but it was "5" in 1.23.2.

"None" will cause trouble scaling the chart (e.g. with inverted sort).

<img width="509" alt="none" src="https://user-images.githubusercontent.com/14329097/78662575-3f2d0800-7903-11ea-83bb-3467ff45672f.png">

**Comment by adrianmroz** [comment]
Could you describe your whole path?

I open data source, add Time (line chart appears) and add another split and I get limit 10. How do you do it?

**Comment by l2dy** [comment]
1. Open http://127.0.0.1:9090/.
2. Drag Time into splits.
3. Drag Channel into splits.

Link: http://127.0.0.1:9090/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADTjTxKoY4DKxaG2A5lHzYYCBEwwBbYshzF8IAKJpyAegCqAFQDCjEADMICNMRpC8AbVBoAngAd5BKfKY1i+hc73OACqawAJuZWIAEwNOhYuAQ+AIwAInpQJnb4pLES9o6E6MTJIAC+ALrFTFB2SGjB1lkKyTQQAnoBENLYUFEKVHDYJAhJmHT4oG4eBHABAcQB3rUEUP55zRBu5BzRoXnkxNgtTUwODZgzBIVMSJIQ9HgiYgUMNQ6erS6hL+2dTi96/BG3tFcbAofJpYgAJAZDPAjdzPaSzJ4EFptDo4ZardYKOBQba7Rr8M6EVpXYSiBClEALBpLSww/SmHbbLGTaZ6fSDSToYYgWyIzb6OCiehMMCIGDZQm87LSbHheQUuyNEgBeLvVHtfAWEDdXrEfpMbBwaTlOBMpjQABKmAARph6EUDkrppxBtcQBMpjMCkA===
