### ISSUE TITLE
Split on boolean dimension has string kind 

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#563]
We don't have boolean kind for Splits. In result, when converting (on table) splits to filter after highlighting, we got error, because we create string filter clause instead of boolean filter clause.

Question is - do we need different kind for splits or additional information about underlying dimension type?

**Comment by mkuthan** [comment]
I would define boolean specific split. Good place to change to disable "limit" for boolean splits. Right now you can set limit to 50 for boolean dims :D

**Comment by adrianmroz** [comment]
Linked #472
