### ISSUE TITLE
is there a way to update config

### ISSUE THREAD

**Issue by holiday12138** [allegro/turnilo#577]
when the cluster‘s dataset were changed，how to update config.yaml to latest，（some datacube were removed or some datacube were added）

**Comment by adrianmroz** [comment]
If you run turnilo in introspect mode - turnilo will update automatically due to cluster changes.
If you run with your own config - you need to update config and restart turnilo
If you use turnilo with --print-config - it runs as one off command, so you need to run it every time something changes.

**Comment by holiday12138** [comment]
> If you run turnilo in introspect mode - turnilo will update automatically due to cluster changes.
> If you run with your own config - you need to update config and restart turnilo
> If you use turnilo with --print-config - it runs as one off command, so you need to run it every time something changes.

I dont understand，I have a own config.yaml now, and have config some items for customization， I want to update data source  and output a new config based on my existing config file

**Comment by holiday12138** [comment]
I mean is it possible to synchronize the data and generate a new configuration file while retaining the original modification

**Comment by adrianmroz** [comment]
Ok, I understand now. 

Sadly, no. You would need to generate new config and merge it with your old by hand or some merge tool.

**Comment by holiday12138** [comment]
all right，I know，thanks
