### ISSUE TITLE
Iframe question

### ISSUE THREAD

**Issue by AlejandroITOP** [allegro/turnilo#587]
Hello, we are implementing turnilo and I would like to ask if it is possible when using iframe mode to show only the graph or graph and filter? avoiding either the top bar. I would also like to know if you have implemented some mode such as read-only to prevent them from being edited.

For example just show the content that is inside the red square in the image :
![Sin título](https://user-images.githubusercontent.com/50695114/76858641-bd8c1200-684f-11ea-9f77-75d3f121bcf8.png)

**Comment by adrianmroz** [comment]
Similar question: #543 

It is not on our priority list but we would welcome such contribution and help with it. Right now there's no simple way to do this.

Please move to #543 with further questions, I'll close this issue.
