### ISSUE TITLE
Turnilo generic JDBC Support 

### ISSUE THREAD

**Issue by ayandad** [allegro/turnilo#589]
Would like find out if Turnilo supports configuring jdbc or odbc  connection.
If yes where can i get steps to do this - i am looking at a way to connect turnilo to prestodb (JDBC connection currently works ok for for presto on other client tools)

**Comment by adrianmroz** [comment]
Turnilo is Druid only and currently supports only native Druid queries. No jdbc/odbc.

**Comment by ayandad** [comment]
> Turnilo is Druid only and currently supports only native Druid queries. No jdbc/odbc.

thanks.
