### ISSUE TITLE
Legend Truncated in Bar Chart View

### ISSUE THREAD

**Issue by DanoOM** [allegro/turnilo#594]
When viewing a bar chart, say over 1 day, with split by hour, the 'hour' is not visible, it get truncated in form: Wed Mar 25 20....

see attachment:
![Screenshot from 2020-03-26 10-00-51](https://user-images.githubusercontent.com/17622079/77674797-548c5480-6f49-11ea-848e-862d746539ef.png)

**Comment by milimetric** [comment]
Maybe just as simple as changing the date format?  Let’s see what we could use:

Wed Mar 25 20...
2020-03-25 10:00

Looks like there’d be space for at least the hour if not minutes.

**Comment by adrianmroz** [comment]
We're rewriting Barchart for cases with split on time and it uses same algorithm for x-axis labels as line chart. If we finish it, this issue would be resolved.
