### ISSUE TITLE
Empty hover box below refresh button

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#604]
In 1.24.0-beta.0, a small rectangle would appear if I hover the pointer over the refresh button.

<img width="167" alt="empty" src="https://user-images.githubusercontent.com/14329097/78662977-f590ed00-7903-11ea-9338-98e42715fdb2.png">

**Comment by adrianmroz** [comment]
So problem is that tooltip has white on white text. Question is - why we don't have tooltips for all icons in header?

**Comment by l2dy** [comment]
Fixed in 1.24.0-beta.1. Thanks!
