### ISSUE TITLE
Line chart coloring without splits has very low contrast

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#606]
Since 1.24.0-beta.0:

![Screenshot_2020-04-07 Turnilo (1 24 0-beta 0)](https://user-images.githubusercontent.com/14329097/78664389-8072e700-7906-11ea-86fe-cd6cb62332fc.png)

Is this intentional?

**Comment by adrianmroz** [comment]
Nope, that's a bug! Thanks for reporting.

**Comment by adrianmroz** [comment]
@cedrics could you look into this? Looks like your last change caused it: https://github.com/allegro/turnilo/blob/master/src/client/utils/styles/_variables.scss#L34 by default those lines are orange, probably something from $brand

**Comment by adrianmroz** [comment]
```

 $main-time-line:          $brand;
 $main-time-area:          rgba($brand, 0.14);
```

here: https://github.com/remerge/turnilo/blob/2528cdffd276d7bd2a9f3590668d843ae988d1fe/src/client/utils/styles/_variables.scss

**Comment by cedrics** [comment]
@adrianmroz will do
