### ISSUE TITLE
Crash after dragging vertical frame borders during first load

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#610]
<img width="1781" alt="nundef" src="https://user-images.githubusercontent.com/14329097/78738068-7e02a280-7983-11ea-865d-b200c410a380.png">

(v1.24.0-beta.1)

**Comment by adrianmroz** [comment]
I set network to slow, launch line chart view, added measure, line chart disappeared and loader showed, I started dragging and can't trigger error. I finish dragging before load completes and after it completes - no success.

Have you some tips how to reproduce this?

Thing is, line chart is going under knife in next version. I see that errors originates from scales/axis computation that I'm planning to change in new version, so if it's not a simple bug I'll ignore it and check with new version.

**Comment by l2dy** [comment]
Try refresh the page and immediately start dragging.

**Comment by l2dy** [comment]
> I set network to slow, launch line chart view, added measure, line chart disappeared and loader showed, I started dragging and can't trigger error. I finish dragging before load completes and after it completes - no success.

Looks like it's only triggered on first load, so you need to refresh the page.

**Comment by mkuthan** [comment]
@l2dy - could you try to reproduce the issue on 1.25, please? Line chart was heavily refactored and it should solve the reported crash as well.

**Comment by l2dy** [comment]
Fix verified, thank you!
