### ISSUE TITLE
Empty legend if measure is re-selected

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#615]
1. Add time and another split.
2. Remove default measure.
3. Add it back.

Link: http://127.0.0.1:9090/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADTjTxKoY4DKxaG2A5lHzYYCBEwwBbYshzF8IAKJpyAegCqAFQDCjEADMICNMRpC8AbVBoAngAd5BKfKY1i+hc73OACqawAJuZWIAEwNOhYuAQ+AIwAInpQJnb4pLES9o6E6MTJIAC+ALrFTFB2SGjB1lkKyTQQAnoBENLYUFEKVHDYJAhJmHT4oG4eBN29xP2ZDgotbR04zRBu5BzRoXnkxNgtTQVMSJIQ9HixAAwHNbNOrS6hd+2dt9J6/BEiCLQnNgo+mrEABIDIZ4EbuTx3by1AjzHaLXBMFqrdYKOBQba7Rr8QqHVonYSiBClEBQfx5fAhUamHbbNEBALEAJ6fSDSToYYgWw3Tb6OCiehMMCIGDZXFcmEgaTo8LyEl2RokALxR4I4IgCZ9PTYODScpwOlMaAAJUwACNMPQikwFZMApxBqcQHAGUzCkA=

![Screenshot_2020-04-20 Turnilo (1 24 0)](https://user-images.githubusercontent.com/14329097/79747719-c5534080-833e-11ea-9902-1be15f49eda4.png)

**Comment by adrianmroz** [comment]
Legend is empty because split is sorted by Dimension. That's because when you remove measure we still need to sort by something so we pick Dimension. After adding measure we don't change sort on split - I think we shouldn't.

**Comment by l2dy** [comment]
> Legend is empty because split is sorted by Dimension. That's because when you remove measure we still need to sort by something so we pick Dimension. After adding measure we don't change sort on split - I think we shouldn't.

I think the new UI is hurting user experience. We should at least add an indicator of which measure / dimension is displayed.

**Comment by adrianmroz** [comment]
If we sort by measure we could show measure title. Don't know what to show when sorting by dimension.

**Comment by l2dy** [comment]
How about displaying the first measure when sorting by dimension? Without a measure the whole component is hidden anyway.

**Comment by adrianmroz** [comment]
We would enter into madness of inconsistency we just left. Chart and Legend sort should always be in sync.

**Comment by l2dy** [comment]
Numbers without any description is confusing to beginners, and sorting is not as intuitive as before. In conclusion, we could do either of

1. Remove numbers from the legend.
2. Add a label on the top right corner showing which measure it is.

**Comment by adrianmroz** [comment]
I'm leaning towards removing numbers. If we present multiple measures on chart we don't have good number to show. 

Imagine that, split on time and Channel (en, es, de). And multiple measures (added, deleted, delta). If we show three charts for each Channel and on each chart we present three measures. Colors would be assigned to "added", "deleted" and "delta". I don't see what we could show as number. Total of "added"? That would confuse users further.

**Comment by adrianmroz** [comment]
I removed measure values in #616

**Comment by adrianmroz** [comment]
@l2dy would you agree that we can close this?

**Comment by l2dy** [comment]
Yes. Thank you!
