### ISSUE TITLE
dimension url is not working?

### ISSUE THREAD

**Issue by exherb** [allegro/turnilo#617]
config dimension url as https://example.com/%s

click on dimension value, the url is not shown as expected.

**Comment by adrianmroz** [comment]
I didn't know about this feature. I found it right now in documentation. How do you expect to work? Where dimension value should be clickable?

**Comment by exherb** [comment]
> I didn't know about this feature. I found it right now in documentation. How do you expect to work? Where dimension value should be clickable?

Yes. misleading by the documentation.

I will submit a pr to resolve this latter

**Comment by adrianmroz** [comment]
You want add this functionality or remove it from documentation? If latter, you'd need remove also `url` field in `dimension.ts`. If former - let's discuss how to implement this.

**Comment by exherb** [comment]
> You want add this functionality or remove it from documentation? If latter, you'd need remove also `url` field in `dimension.ts`. If former - let's discuss how to implement this.

Add this functionality

Maybe make the cell value clickable at hover menu?

**Comment by exherb** [comment]
https://github.com/allegro/turnilo/blob/2751dbcaee9488c05b26cecaec0beaefb1c9eeee/src/client/components/segment-action-buttons/segment-action-buttons.tsx#L95

I find some related code, but this component is not referenced by any other component or view.

**Comment by adrianmroz** [comment]
> Maybe make the cell value clickable at hover menu?

But which "cell"? We present dimension values in multiple places and in most cases clicking on it does something.

**Comment by exherb** [comment]
https://github.com/allegro/turnilo/blob/2751dbcaee9488c05b26cecaec0beaefb1c9eeee/src/client/components/highlight-modal/highlight-modal.tsx#L36

I think all dimension value should be shown as url tag if dimension’s url is not empty.
