### ISSUE TITLE
500 Query error when custom measures used together with the time-shift

### ISSUE THREAD

**Issue by rathko** [allegro/turnilo#621]
Using both the time-shift feature and the custom measures that include division results in a 500 error. 

Steps to replicate:
* add custom measure that includes division (CTR, EPC, etc)
* select period of time and enable time-shift (MoM, YoY or similar)
* add any dimension to group on
* Turnilo invariably throws the `Query error, error with response 500`

**Comment by adrianmroz** [comment]
Duplicate: https://github.com/allegro/turnilo/issues/505 ?

**Comment by rathko** [comment]
I can confirm that adding a [fallback](https://plywood.imply.io/expressions#fallback) as suggested in #505 helps with this, thanks!

**Comment by adrianmroz** [comment]
Let's keep this issue open. 

We should check if similar case occurs when picking Expression series from menu and selecting division. Probably we should handle that case too.

**Comment by adrianmroz** [comment]
> We should check if similar case occurs when picking Expression series from menu and selecting division. Probably we should handle that case too.

It is handled by plywood/druid!

**Comment by rathko** [comment]
So it seems that fallback does help if a custom measure based on a division is implemented via a Turnilo config but not when it is added from UI as a Turnilo calculated measure. One option could be to specify a `0` as a fallback for all such measures perhaps? In this case user will see 500 error.

**Comment by adrianmroz** [comment]
I need link for wikipedia data cube with replicated issue. I couldn't reproduce this error on my end and I don't see how it's different from config measure. Maybe there's something else that causes error?
