### ISSUE TITLE
No data shown on datacube when having that with custom config and more cubes without

### ISSUE THREAD

**Issue by DixxieFlatline** [allegro/turnilo#625]
Hello, just to report this as I don't have spare time to investigate. I had dockerized turnilo running while having only one datacube on druid with my custom config and everything runned flawlessly. Then I added another datacube on druid and turnilo detected it, this one didn't had any custom config. Both were selectable, but only data was shown on the second one -non configured-. When I added a custom config for the second one, both worked as they should.

**Comment by adrianmroz** [comment]
What you mean by saying it was selectable but no data was shown?

**Comment by DixxieFlatline** [comment]
I mean that when opening the base url where Turnilo is, instead of opening the configured datacube panel as it did before adding the second to Druid, it correctly shows both datacubes to be selected. But only in the new one data is shown. In the original, the configured one, metrics are 0 and dimensions show no data. This was solved adding a custom config for the second cube.

**Comment by mkuthan** [comment]
@DixxieFlatline - Without druid datasources configuration and turnilo configuration we are not able to reproduce the issue, I'm affraid.

**Comment by DixxieFlatline** [comment]
I am sorry to say that I cannot share none of them, so I guess I'll close this.
