### ISSUE TITLE
Pinboard does not refresh when auto update is turned on

### ISSUE THREAD

**Issue by syed-imdad** [allegro/turnilo#635]
Pinboard is not getting refreshed with the refresh options.

We always have to hide pinboard and then back on to show the updated results, only graphs are being updated with refresh options

**Comment by adrianmroz** [comment]
We should pass `lastRefreshRequestTimestamp` from state here: https://github.com/allegro/turnilo/blob/master/src/client/views/cube-view/cube-view.tsx#L642 all the way to `pinboard-tile` and check here: https://github.com/allegro/turnilo/blob/master/src/client/components/pinboard-tile/utils/should-fetch.ts just as in https://github.com/allegro/turnilo/blob/master/src/client/visualizations/base-visualization/base-visualization.tsx#L165

**Comment by syed-imdad** [comment]
any updates here

**Comment by mkuthan** [comment]
@syed-imdad feel free to make a fix and open pull request
