### ISSUE TITLE
Applied filters and splits keeping state after switching to a new data cube

### ISSUE THREAD

**Issue by jmbowles** [allegro/turnilo#636]
v 1.24

After a filter and split is applied to a data cube, when switching to a different data cube, that same filter and split is applied to the data cube switched to. Very powerful when this type of behavior is needed and when data cubes have common dimensions. Also saves time to prevent user from selecting the same filters and splits between cubes. However, when that filter and split doesn't have those same dimensions in the next data cube, the message "The Table requires at least one split" is displayed instead of the Totals like it normally does. 

I'm wondering if there's a way to disable this behavior in the configuration or configure on a data cube basis. 

Thanks for the help. Keep up the good work.

**Comment by adrianmroz** [comment]
> I'm wondering if there's a way to disable this behavior in the configuration or configure on a data cube basis.

No, there is not and we're not planning to add it.

That said, I think that's a bug. Right now, if you remove split from table, turnilo will change to totals visualisation. It should work the same when switching cube in your scenario. I'll look into it and try to fix it. 

If that would not be possible, we could return to initial design, where keeping state between states is on "opt in" basis. There was "group" prop on data cube definition, and state was kept only between cubes that belong to the same group.

**Comment by jmbowles** [comment]
Thanks for the info. The "group" prop you mentioned  might do the trick. Is that something I could define in my config.yaml? Just add "group: some_name' to each of my data cubes that share common dimensions ?

**Comment by adrianmroz** [comment]
Unfortunately, that’s how it worked before 1.24 :(

**Comment by adrianmroz** [comment]
Can I hijack this issue as a bug report? If we will smoothen behaviour, so in your case turnilo would switch to Totals, would you be satisfied?

**Comment by jmbowles** [comment]
I think Totals would be the best behavior. Thanks again for the help. I really appreciate it.

**Comment by adrianmroz** [comment]
Can you run turnilo from branch to check if #643 fixes your issue? It looks fine from my side. If not, you would need wait a little for 1.26.
