### ISSUE TITLE
February 29 display with year time shift

### ISSUE THREAD

**Issue by milimetric** [allegro/turnilo#640]
When time shifting by a year on a time period that crosses from February to March, if one year is a leap year and the others are not, you get this drop to zero:

![Screenshot from 2020-06-12 09-53-02](https://user-images.githubusercontent.com/1038928/84510409-13c3f200-ac93-11ea-9670-ecbf747c442a.png)

This is confusing at first, until you realize that it's just rendering February 29th 2019 as zero since that day doesn't exist.  I think it would be slightly better to display it as a gap.  If the maintainers agree I can submit a patch.

**Comment by adrianmroz** [comment]
Turnilo always presents missing data on line chart as drop to base. Why we should change it in this case? 

We accept patches and would be grateful, but in this case I think we need discuss what we want to fix. In my opinion we should keep behaviour consistent. Always drop to base or never.

**Comment by milimetric** [comment]
I see.  Makes sense to be consistent.  Have you already gone over the ambiguity between an actual zero value and missing data?  That's pretty much the one downside with always dropping to zero, but if that conversation already happened, no need to revisit.

In case that conversation hasn't happened, my personal preference is that missing values are just gaps so they can be differentiated from zero values.  If others feel this way, I'll start a patch, otherwise no big deal.

**Comment by adrianmroz** [comment]
We will discuss it internally on Monday. But any feedback is welcome! 

To be honest I don’t see good reason for current behavior.

**Comment by adrianmroz** [comment]
We discussed this a little and I changed my opinion 180 degrees!

I checked responses and behaviour of druid/plywood and in most cases we get literal 0 as a value. Even in this case. So it is not an issue of presentation. And there are more similar cases - shift May one month and you got zeroed 31st. And without time shift - sometimes measures don't exist in range where some other measure do - in this case we also get literal zero.

So I don't think we can fix this without some special edge cases in code and I'm not very comfortable with adding such conditions to the codebase. 

On more high level I also think that dropping to zero is good behaviour - most measures are defined as counts or long sums (hlls and histograms are sums in disguise) and for that operations zero is neutral element.

**Comment by milimetric** [comment]
Ok, this makes a lot of sense.  Sorry for not checking what plywood actually returns.  That makes perfect sense with aggregates.  I'll close this.  If other folks raise the same issue in the future, maybe just a simple tooltip would help, only when time shifting is active.  Something like "When time-shifting, some dates don't exist (like 2019-02-29).  Measures default to zero in these cases."
