### ISSUE TITLE
Simple enhancement request: URL shortener client forwarding

### ISSUE THREAD

**Issue by milimetric** [allegro/turnilo#656]
Summary: we want to use a URL shortener that wants the client's IP instead of our turnilo server's IP.

Our (Wikimedia Foundation) [URL shortener](https://meta.wikimedia.org/wiki/Wikimedia_URL_Shortener#Security) has a number of restrictions that prevent broader use (it's meant to shorten WMF-hosted URLs for humans (using rate-limiting)).  To call it, ideally we could pass the client's IP or XFF header when calling the configured `shortenerFunction`.

I'll send a pull request that does this in a moment, I just wanted to file the issue so we can talk it over if needed.

For reference:

* Original [shortener implementation](https://github.com/allegro/turnilo/pull/232).  I looked through and didn't see discussion either way on this particular idea.
* Our [config patch](https://gerrit.wikimedia.org/r/c/operations/puppet/+/622600/2/modules/turnilo/templates/config.yaml.erb) that doesn't work because of our security measures.

**Comment by adrianmroz** [comment]
I assume you want to get client IP from `Request` object from `express`, and pass it to shortener function there: https://github.com/allegro/turnilo/blob/62e53b29e0a2fe5d9232382110bd27197d0636cf/src/server/routes/shorten/shorten.ts#L27 ?

Some „metadata” object as third parametr would be good - we could expect that more additional information would be needed in the future.

**Comment by milimetric** [comment]
Yep, I'm just wringing my hands over how fancy I should get looking at proxies and XFF headers.  Let's discuss on the PR, sending now.

**Comment by milimetric** [comment]
https://github.com/allegro/turnilo/pull/668 is a quick follow up, with that everything should work great.
