### ISSUE TITLE
Plugin system for turnilo backend

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#666]
We would like to allow loading custom middleware for turnilo to augment its behaviour.

First idea is to define `modules` or similar named field in config. It would be an array of path's that are valid for `require` function resolution algorithm. Such filed would be loaded and turnilo would assume that they export specific field which is a function. That function would be called with `app` instance (it's an express application). 

Of course it is opening turnilo to custom code but administrator is responsible to ensure that loaded modules are safe.

Possible use cases:
1. We could move url shortening endpoint into separate package and everybody could customise it as they wish
2. auth/openid integrations
3. entry point for more sophisticated logger 

Todo:

- [x] read config for plugins and run `plugin` method from `require`d files
- [x] pass there server settings, plugin settings and promise with app settings
- [x] prepare map on `request` object for communication between plugins
- [x] catch errors in plugins and show them on `errorLayout`

**Comment by adrianmroz** [comment]
We also found `auth` module in code: https://github.com/allegro/turnilo/blob/master/src/server/config.ts#L206..L230

Do any of you use it? We'd like to deprecate it so we get only one way to load modules. If you use it, please inform if you could migrate or what's missing in my proposal. @cedrics @l2dy @alexbusu @moshederri @KarolakJakub

**Comment by adrianmroz** [comment]
Another idea - plugins could get additional configuration from config file. So format of config could look something like:

```
plugins:
  - name: some_name
    module: path/to/module.js
    config:
      - field1: value1
      - field2: [composed, field]
```

Such config would be passed to module beside `app` instance.

**Comment by mkuthan** [comment]
I really like proposed config file snippet.

**Comment by alexbusu** [comment]
> We also found `auth` module in code: https://github.com/allegro/turnilo/blob/master/src/server/config.ts#L206..L230
> 
> Do any of you use it?

Not using it. :heavy_check_mark:

**Comment by adrianmroz** [comment]
Two nice things to consider:

1. Find a way to let plugin go straight to `errorLayout` and show some message
2. Define field on `req`, where plugins could safely store information to use in different plugin

**Comment by l2dy** [comment]
Any developer-facing documentation for this? Is it possible to publish an auth plugin on npm and allow others to use it?

**Comment by adrianmroz** [comment]
> Any developer-facing documentation for this?

Not ... yet. It is very early and experimental version and we're trying to use it internally for few cases. So stay tuned.

But our goal is to allow users write their own plugins and even move some turnilo features to plugins (like url shortener or log system). Our main driver is auth but our plugin is tied to our infrastructure so we won't publish it. Nothing stop others from publishing theirs and plugin systems can load anything that `require` can load.
