### ISSUE TITLE
Calculated metrics incorrect with time shift

### ISSUE THREAD

**Issue by TLischkaRemerge** [allegro/turnilo#673]
We have a Turnilo-based dashboard which produces tables showing revenue, broken down by different sources using calculated metrics. We use a time shift to show the revenue for the current time period and a previous period, usually one day. The calculated metrics for each conversion type are revenue / conversion_count. If I understand correctly, this should mean that with a time shift, the values returned would be:

- (current_revenue / current_conversion_count)
- (previous_revenue / previous_conversion_count)

Instead the return values seem to be:

- current_revenue / (current_conversion_count + previous_conversion_count)
- previous_revenue / (current_conversion_count + previous_conversion_count)

We are using a druid backend and turnilo seems to correctly set the time ranges for both calculations in the plywood query it builds. It could be related to how plywood translates the query into a druid query.

I'm not sure if this is a bug or the expected behavior. It's expected, do you know how we could correctly request the values described above?

**Comment by adrianmroz** [comment]
Hi,

That's definitely a bug! Thanks for catching that.

To easily reproduce one can run `npm run start:examples` and go to [this url](http://localhost:9090/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhqZqJQgA0408SqGOAygKZobYDmZe2MCClGALZNkOJvhABRNAGMA9AFUAKgGEKIAGYQEaJgCcuAbVBoAngAdxBIeMp6mGiTfU2ACvqwATI6E8w96Fi4BK5KAIwAEupQuub4ALRhAhZWIAjoTDEgAL4AunmUUOZIaEa5hR6Z+MYg9hr6TNgyqXCenkye6hqYeoLo+CYpEkwAHnAyaOpgiDCpOcmWEsJwsPbzoHUNTakymDDYk5Tdvf14g4sEo+OH4DNz2Qupy6viDxsOW80Sre2dRz19SZnQhDS5jCZTO4SeYgi4gUbmexQKBBdQIpEonADECYSwBejBECeCCQdrqTb2bYSXb7SbZAogcwQbDYDoAEQgwmwmO51RAMgAFnAWUwEOpsHBhEVxrYQNAAEqYABGxBA5UZzNZngYPSBIB+HRcnKYDAFEA0etCACYotkgA===)

**Comment by adrianmroz** [comment]
Probable cause:


[Here](https://github.com/allegro/turnilo/blob/master/src/common/models/expression/concreteArithmeticOperation.ts#L76
), we need to filter measure expression with correct [TimeShiftEnv](https://github.com/allegro/turnilo/blob/master/src/common/models/time-shift/time-shift-env.ts)
