### ISSUE TITLE
problem with build:dev

### ISSUE THREAD

**Issue by wmeler** [allegro/turnilo#678]
Readme says that for development we should build project with npm run build:dev which is missing.
```
$ npm run build:dev
npm ERR! missing script: build:dev
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     build
npm ERR!     build:server

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wmeler/.npm/_logs/2020-11-20T10_06_55_072Z-debug.log
```

**Comment by adrianmroz** [comment]
Yeah, there's some disparity between documentation and available npm scripts. 

Nevertheless, old `npm run build:dev` was buggy. `npm run start:dev` runs turnilo and enables dev mode for frontend code. If you want to rebuild server, you need to run `npm run build:server` manually.

I'll fix documentation soon and maybe later I'll look if it's possible to have watch and module replacement on server.
