### ISSUE TITLE
Bookmark / Save reports

### ISSUE THREAD

**Issue by mihirtech** [allegro/turnilo#688]
There are multiple fact cubes, dimensions and metrics, and hence different combination of these entities to solve a particular reporting use-case. It is painful to reapply same set of filters/splits/dates to go back to same reporting view.

The user should have an option to:
- Bookmark Save the link (and give that a tag/name)
- Access this link in the future to directly view the report.

**Comment by adrianmroz** [comment]
Turnilo does not have concept of users (as user accounts) and is a stateless application. I don't think this is possible with these limitations.

**Comment by mihirtech** [comment]
Sure, that is fair. Any chance this could be possible at a device level? In the majority of cases, users would continue using the same device, so having bookmarks at a device level still solves most of such scenarios.

**Comment by adrianmroz** [comment]
Let's combine this idea with #72! We could have saved reports and if user define sane defaults we could treat them as entry points to favourite cubes.
