### ISSUE TITLE
when remove split，also remove the legend from pinboard at the same time

### ISSUE THREAD

**Issue by beibm** [allegro/turnilo#69]
if line-chart visualization have two split（such as： channel and comment length），the first split(e.g channel) is acted as Legend,  the second split(e.g comment length) acted as x-axis。
first step： remove the second split(e.g comment length)。
next step： remove the first split(e.g channel)，then a error appeared!
so,
when remove the second split(e.g comment length), should also remove the legend from pinboard at the same time。

**Comment by rafalnowak** [comment]
Thanks for raising this issue. I've checked behaviour you described and it looks like a bug. We will look into it shortly.
