### ISSUE TITLE
Update `node-sass` dependency to 4.14.1 to support Node.js 14?

### ISSUE THREAD

**Issue by harry-xiaomi** [allegro/turnilo#733]
See https://github.com/sass/node-sass/releases.

**Comment by adrianmroz-allegro** [comment]
That's interesting. Our CI checks build on node 14 and it works. But under your link, it says that node-sass `4.13.1` supports only up to 13 ...

**Comment by harry-xiaomi** [comment]
No support means that upstream does not build binaries for and have not tested it against that Node.js version, but it could still be working.

They also have a support table for different Node.js versions: https://github.com/sass/node-sass/blob/master/README.md#node-version-support-policy.

**Comment by harry-xiaomi** [comment]
@adrianmroz-allegro Could you update it?
