### ISSUE TITLE
Faulty channel in resource pool

### ISSUE THREAD

**Issue by tanisdlj** [allegro/turnilo#767]
Hi! We're seeing this error quite often.

Environment is Debian 10, Nodejs v14.16.1, Turnilo 1.32.0

```
error: Unknown exception: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
Error: Unknown exception: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
    at /usr/local/lib/node_modules/turnilo/node_modules/plywood-druid-requester/build/druidRequester.js:288:45
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/turnilo/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:327:22)
    at finishMaybe (/usr/local/lib/node_modules/turnilo/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/usr/local/lib/node_modules/turnilo/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

From time to time also Turnilo ends up getting a 502 in all the queries and I need to restart it. Funny enough, when the same query from Turnilo's host is sent straight away to Druid (without using Turnilo's backend), it answers properly within 2 seconds, while turnilo keeps hitting a 502 after a long time.

Not sure if both issues are connected, but there is something odd in this.

Thanks a lot!

**Comment by adrianmroz** [comment]
To be honest, I'm puzzled why you get error from jboss. Don't you have something between turnilo and Druid?

**Comment by tanisdlj** [comment]
Hey, thanks for the quick answer!
I tried two schemas, both with the same result, before creating this issue:
Turnilo -> Druid Router -> Druid Broker
and
Turnilo -> Druid Broker (avoiding the router).

Same problem. It is really odd, as when we see Turnilo failing and getting only 502s, if I ssh into the server and launch the same query, but directly to the broker, it answers really fast. 
My first idea was a firewall, dns/network problem, but the fact that from the same machine works straight away discarded that theory.

Also, the only way I found to fix it is restarting turnilo. Except the error log y reported here, there is nothing in the logs "while" failing :(

**Comment by adrianmroz-allegro** [comment]
I don't think I can help you. We use plywood-druid-requester library to connect to Druid, and all I can see here is some network issue between this library and your Druid instance. I don't say that turnilo can't be at fault here - just that I don't know what's happening :) Maybe @mkuthan has some ideas?

**Comment by tanisdlj** [comment]
Today I've got once the `Faulty channel in resource pool` from Druid console itself, so my bet is that is not in turnilo's side the issue.
Thanks anyway :D

**Comment by adrianmroz-allegro** [comment]
Feel free to reopen, if you get something new :)
