### ISSUE TITLE
Add support for custom file names

### ISSUE THREAD

**Issue by kottameister** [allegro/turnilo#772]
Hi,

I noticed that Export to CSV doesn’t use a descriptive name in the file name any more, but simply turnilo-export.csv. It might be related to https://github.com/allegro/turnilo/pull/747. Would it be possible to support encoding without hardcoding the file name?

Thanks

**Comment by adrianmroz** [comment]
Hi, 

Yes we removed dynamic file names for exported csv/tsv. Code responsible for this was convoluted and unreliable. Names weren’t good either. For sure we’re not going to bring it back. 

But, we’re open to suggestions how file names should look. Feel free to submit some reasonable schemes and we could discuss if they’re feasible. 

Cheers!

**Comment by kottameister** [comment]
Hi,

Thanks for the response. Could there be a configurable template for the file name so that user doesnt have to specify it every time? For our use case, we'd like something like <report_id>_<starttime>_<endtime>

**Comment by adrianmroz-allegro** [comment]
I don't think we want to add filename template to config. 

> <report_id>_<starttime>_<endtime>

Sounds doable, can I get some feedback from others?

**Comment by aagoath** [comment]
@adrianmroz the generated file name would be good. is there a unique `report_id` generated when report is built, which can be used here? I think  `<starttime>` & `<endtime>` will be valuable if they are in form of `yyy-mm-dd-hh-mm-ss`.

**Comment by adrianmroz** [comment]
> @adrianmroz is there a unique `report_id` generated when report is built, which can be used here?

Nope. I was thinking that would be data cube id.

**Comment by adrianmroz-allegro** [comment]
@aagoath @kottameister What do you think about this:
![image](https://user-images.githubusercontent.com/78143552/132001831-4dfb16e0-f3a3-49fa-b003-7999be05ecf5.png)

**Comment by aagoath** [comment]
@adrianmroz this looks exactly what we were looking for. thanks.
