### ISSUE TITLE
Unable to use `print-config` with `--config` parameter

### ISSUE THREAD

**Issue by ivanmatyash** [allegro/turnilo#789]
Hi, dear community!

I faced some issue with printing turnilo config. Druid and Turnilo are deployed to different hosts and Druid requires the Turnilo to be authorized in order to fulfill requests.

So we have next **config.yml** file:
```
port: 9090

clusters:
  - name: druid
    type: druid
    url: https://<druid_broker_url>
    sourceListScan: auto
    sourceListRefreshOnLoad: true
    sourceListRefreshInterval: 100000

    requestDecorator: './druid-request-decorator.js'

    decoratorOptions:
      myUsername: turnilo
      myPassword: <password>
```

**druid-request-decorator.js**:
```
exports.version = 1;

// logger - is just a collection of functions that you should use instead of console to have your logs included with the Swiv logs
// params - is an object with the following keys:
//   * options: the decoratorOptions part of the cluster object
//   * cluster: Cluster - the cluster object
exports.druidRequestDecoratorFactory = function (logger, params) {
  var options = params.options;
  var myUsername = options.myUsername; // pretend we store the username and password
  var myPassword = options.myPassword; // in the config

  if (!myUsername) throw new Error('must have username');
  if (!myPassword) throw new Error('must have password');

  logger.log("Decorator init for username: " + myUsername);

  var auth = "Basic " + Buffer(myUsername + ":" + myPassword).toString('base64');

  // decoratorRequest: DecoratorRequest - is an object that has the following keys:
  //   * method: string - the method that is used (POST or GET)
  //   * url: string -
  //   * query: Druid.Query -
  return function (decoratorRequest) {

    var decoration = {
      headers: {
        "Authorization": auth,
        "X-I-Like": "Koalas"
      }
    };

    // This can also be async if instead of a value of a promise is returned.
    return decoration;
  };
};
```

Starting turnilo by this command looks good:
```
turnilo --config ~/config.yml -v
```
<details><summary>Some logs here</summary>

```
Using config /var/www/turnilo/config.yml
Starting Turnilo v1.32.0
Cluster druid : requestDecorator as string and decoratorOptions fields are deprecated. Use object with path and options fields
Adding cluster manager for 'druid' with 0 dataCubes
Cluster druid: Loading requestDecorator
Cluster druid creating requestDecorator
DruidRequestDecoratorFactory Decorator init for username: turnilo
Cluster 'druid' will refresh source list on load
Attempting to connect to cluster 'druid'
vvvvvvvvvvvvvvvvvvvvvvvvvv
Requester rq92284 sending query 1:
{
  "queryType": "status"
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
(node:89410) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Turnilo is listening on address :: port 9090

...


Connected to cluster 'druid'
Setting up sourceListRefresh timer in cluster 'druid' (every 100000ms)
Cluster 'druid' is running druid@0.21.1
Introspecting all sources in cluster 'druid'
vvvvvvvvvvvvvvvvvvvvvvvvvv
Requester rq92284 sending query 2:
{
  "queryType": "sourceList"
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Requester rq92284 got result from query 2: (in 6ms)
[
  [
    "xxx",
    "yyy",
    "zzz"
  ]
]
^^^^^^^^^^^^^^^^^^^^^^^^^^
```
</details>

But when I try to execute the following command - I get the error:
```
turnilo --config ~/config.yml -v --print-config
```
<details><summary>Logs here</summary>

```
Cluster druid : requestDecorator as string and decoratorOptions fields are deprecated. Use object with path and options fields
vvvvvvvvvvvvvvvvvvvvvvvvvv
Requester rq53077 sending query 1:
{
  "queryType": "status"
}
^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvvvvvvvvvvvvvvvvvvvvvvvv
Requester rq53077 got error in query 1: 401 - "<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" (in 58ms)
^^^^^^^^^^^^^^^^^^^^^^^^^^
No labels for sentryDSN, please fix this in 'common/models/labels.ts'
There was an error generating a config: Could not find any data cubes, please verify network connectivity
```
</details>

Please tell me what am I doing wrong?

Thanks in advance!

**Comment by adrianmroz-allegro** [comment]
I don't think we anticipated case with `--config` and `--print-config` options enabled simultaneously. What are you trying to achieve?

**Comment by ivanmatyash** [comment]
Hi @adrianmroz-allegro 
Just wanted to start turnilo with my custom `config.yaml` file. And trying to get auto-generated config, as mentioned in docs:

> Turnilo can be configured with a config YAML file. While you could write one from scratch it is recommended to let Turnilo give you a head start by using it to generate a config file for you using the default introspection.

Is it possible ?

**Comment by mkuthan** [comment]
```
turnilo --druid http[s]://druid-broker-hostname[:port] --print-config
```

**Comment by adrianmroz-allegro** [comment]
> Is it possible ?
For sure it is not intended to run `--print-config` with existing config :) 

From your logs I guess there is some problem with access. Probably code paths from `--print-config` does not use your request decorator with authentication headers. I'll try to reproduce this on my setup. If it's simple issue we'll probably fix it, but I don't think we're going to invest a lot of time here.

**Comment by ivanmatyash** [comment]
> > Is it possible ?
> 
> For sure it is not intended to run `--print-config` with existing config :)
> 
> From your logs I guess there is some problem with access. Probably code paths from `--print-config` does not use your request decorator with authentication headers. I'll try to reproduce this on my setup. If it's simple issue we'll probably fix it, but I don't think we're going to invest a lot of time here.

Thanks, I got your point.
In my config.yml, I just specified the parameters for connecting to the cluster (since it requires authorization). I was expecting to receive a config that would contain information about the dataCubes, dimensions, metrics, etc.

**Comment by adrianmroz-allegro** [comment]
Ok, I checked few things. 

`No labels for sentryDSN, please fix this in 'common/models/labels.ts'` is definitely error on our end and we will fix it shortly. But that should only print some warning in console, nothing else.

I reproduced your second error when I put wrong credentials. Could you check if you pass correct credentials? I don't see that you pass them via config and inside decorator you don't have them hardcoded either. Probably you sniped them before posting on GitHub, but please check again.

To my surprise, your use case worked for me! We should hunt down error in your setup.
