### ISSUE TITLE
Visualisation state does not persist between data fetches

### ISSUE THREAD

**Issue by adrianmroz-allegro** [allegro/turnilo#805]
Example:
1. Table viz
2. Resize left gutter of the table
3. Change splits
4. Left gutter go back to initial width

Problem:
After any essence changes, DataProvider unmount chart, show loader and mount new instance of chart, thus state is initialised with default values.

Solution:
Lift state. Need to pass to ChartPanel a component that has closed over some state.

**Comment by adrianmroz** [comment]
Fixed via #806
