### ISSUE TITLE
excesive max time checks in time-monitor

### ISSUE THREAD

**Issue by wmeler** [allegro/turnilo#817]
I've been chasing strange turnilo behaviour which occurs with druid timeouts and is clear that time-monitor is broken and even can cause druid overload.

doChecks method https://github.com/allegro/turnilo/blob/master/src/common/utils/time-monitor/time-monitor.ts#L71 has simple boolean doingChecks guard. The problem is it is always false due to Promise.all behaviour. Promise.all expect iterable of promises.
Unfortunately checkTags is a Map which is iterable of tuples that are instant-resolved promises :(. That causes to push new requests every second  - whenever doChecks is called.

The simple fix is to add .values() at the end of line 
const checkTasks = timeTags.filter(this.isStale).map(this.doCheck).values();

It would be nice to implement some kind of back-off in case of error. Now if max time request fail it would be repeated next time doChecks is called because corresponding TimeTag is not updated. Maybe we should update it with previous value on error?

**Comment by adrianmroz-allegro** [comment]
> Unfortunately checkTags is a Map which is iterable of tuples that are instant-resolved promises :(. That causes to push new requests every second - whenever doChecks is called.
> 
> The simple fix is to add .values() at the end of line const checkTasks = timeTags.filter(this.isStale).map(this.doCheck).values();

Yup, that's a bug. Could you file a PR with fix?

> It would be nice to implement some kind of back-off in case of error. 

You can utilise retry mechanism on cluster for this. `retry` property in [cluster configuration](https://github.com/allegro/turnilo/blob/master/docs/configuration-cluster.md#configuring-the-clusters)

> Now if max time request fail it would be repeated next time doChecks is called because corresponding TimeTag is not updated. Maybe we should update it with previous value on error?

In essence, you want to update only `updated` field of timeTags? Could work, but looks hacky.

**Comment by wmeler** [comment]
We could implement some sort of exponential back-off. If we introduce errorCountSinceLastSuccesfullUpdate property in TimeTag   we could modify isStale to use it in calculation f.e:
  now - timeTag.updated.valueOf() > regularCheckInterval + (1 << timeTag.errorCountSinceLastSuccesfullUpdate) * 1000

Is it worth doing?

**Comment by adrianmroz-allegro** [comment]
> We could implement some sort of exponential back-off.

I don't think that's good idea because that would clash with general retry system. 

In general I admit that running failed checks every second is too much. But I think we should fall back to just one minute. Maybe your first proposal with changing `updated` field is sufficient. For sure it is simple.

**Comment by wmeler** [comment]
OK, lets follow that way - do you think that it is necessary to change the name of TimeTag.updated field to something like updateAttemptAt ?

**Comment by adrianmroz-allegro** [comment]
`lastChecked`? @mkuthan dare to join a little bike shedding? :)

**Comment by mkuthan** [comment]
lastChecked looks good for me

**Comment by adrianmroz-allegro** [comment]
@wmeler I took liberty to copy your code and add few cleanups in #819

**Comment by adrianmroz-allegro** [comment]
Let's close this issue when we merge #819 in :)
