### ISSUE TITLE
Exclusion filter does not filter out 'null'

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#868]
The exclusion filter does not filter out 'null' value. It is independent of the visualisation type.

Scatter plot:
https://turnilo.app/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhQDG6aApgE4AOCmaIANONPEqhjgMplobYDmUfKCgALTAHdOMALYy4FAJ74AZoihkAvkwwyyyHGXwgAomiIB6AKoAVAMKMQKiAnIUheANqg0iqkYJdIyYKMhVjIMcggAVKLAATD28QeJgKdCxcAmiARgBNRyhyKnwAWhydPwCQBHQyIpBNAF1tHyrjIooIAUdQ8IIiCF8AOTg9RzgiDiyQbscwRBh6/E8QbBgEBBAmpmw6fDQKJeamKBohpLb/DsPu/kd4iD1sKEzjQZGx4MJMCno8UB9YxweLxMjxKLtAgaLrLJiPUJTN4EMHEMjYR49Jj+LqYCEERpMJAyIb4ACsAAYToQ4ssvICwpR0URqiCwRCmCpfvJ/ldqmC1Bt6EwFgglsZCSBfNcCHo4LBQoSGSomdgWcYwQgeODHFyKDzhFKoSkwnAhfNFtVJdLqnKFUZqVRuthwQARJ7o144JI7EBO7Au+KcX7/EBsnWaIA==

Grid:
https://turnilo.app/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwgDmAThACYgA0408SqGOAygKZobaFT7YwILUMAWxbIcLfCACiaAMYB6AKoAVAMJUQAMwgI0LYtzwBtUGgCeABwkFhE6sRabJtjbYAK+rGUMmQZGMToWLgEbgCMAJoaUHoW+AC0YYKW1iAI6CwxIAC+ALrZlKYpkjGknBoOTgSyEOYAcnAiGnCyjCEgELjUYIgwmfhGILz8ILnU2Jho+GjEfXnUUBZIaD5FViUznYQaZBAi2FDBkjX1jXYgUJjEU3iglZJwZGQsFMnrBFCe/dS7Dq1HBGeUFkLGwu3K1CspEwFAIOWoSCEtXwAFYAAzzC5fVYgSr6UEgh5PF4aTRXITofBrVLPTRwPhTbq9VLwkDmd4gERwWAOeF3Rz47CEwEsBBsEnUMnECk3amSWn03QaHoIPqSVns1JcnkSTEWTrYF4AET2oMOOB8YxA+uwhrITCuNxAj2eFGyQA=

**Comment by adrianmroz-allegro** [comment]
We don't have any guarantees about values inside string dimensions. They can hold null or any other value.

Right now we eagerly convert all values to string [here](https://github.com/allegro/turnilo/blob/master/src/client/components/selectable-string-filter-menu/string-values-list.tsx#L51)
We should do this more lazy, so we keep original values and show stringified version on UI. Of course that will lead to confusion if non-string value evaluates to existing string value. But I thinks that's on dataset administrator.

**Comment by adrianmroz-allegro** [comment]
Please check: https://turnilo-bugfix-non-string-values-in-string-filter-gmbbyye42a-ew.a.run.app/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwgDmAThACYgA0408SqGOAygKZobaFT7YwILUMAWxbIcLfCACiaAMYB6AKoAVAMJUQAMwgI0LYtzwBtUGgCeABwkFhE6sRabJtjbYAK+rGUMmQZGMToWLgEbgCMACIaUHoW+AC0YYKW1iAI6CwxIAC+ALrZlKYpkjGknBoOTgSyEOYAcnAiGnCyjCEgELjUYIgwmfhGvPy51NiYaPhoxH151FAWSGg+RVYlU52EGmQQIthQwZI19Y12IFCYxBN4oJWScGRkLBTJqwRQnv3U2w6tBwSPUFkLGw23K1CspEwFAIOWoSCEtXwAFYAAyzM4fZYgSr6YFAu4PJ4aTQXITofArVKPTRwPgTbq9VKwkDmV4gERwWAOHIjEAWTrYJ4RHbA/Y4HwgWQACzg2EFCA02BO8xap2gACVMAAjcYgXn8uVPJgXK4ge6PCjZIA=
