### ISSUE TITLE
Authentication module for enabling limited access

### ISSUE THREAD

**Issue by mdeora** [allegro/turnilo#88]
Does it have authentication for enabling limited access ?

**Comment by mkuthan** [comment]
For authentication I would recommend to use any reverse proxy (e.g apache, ngix, haproxy, traefik, etc.) in front of Turnilo (it could be also configured as load balancer for multiple Turnilo instances). There are many authentication methods implemented by reverse proxies (e.g ldap/active directory) so it does not make a lot of sense to duplicate this effort in Turnilo.

Authorization is a different story, it would be nice to add support for [Druid Basic Security](http://druid.io/docs/latest/development/extensions-core/druid-basic-security.html) in Turnilo. Access could be limited on datasource / data cube level then. But this is not on the roadmap yet.

**Comment by mdeora** [comment]
Thanks for the response, I meant Authorization - data cube level access control etc.
