### ISSUE TITLE
Can‘t drag and drop dimension in Microsoft's edge browser

### ISSUE THREAD

**Issue by beibm** [allegro/turnilo#89]
Can‘t drag and drop dimension to split(or filter) in Microsoft's edge browser!

**Comment by mkuthan** [comment]
Thanks for reporting, on daily basis we and our internal Allegro users do not use Microsoft browsers so this kind of bugs are undetectable :(

**Comment by rafalnowak** [comment]
@mkuthan https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ - it can be helpful in such cases.

**Comment by beibm** [comment]
I think that simply catching the exception in dimension-list-tile.tsx dragStart method，such as：

dragStart(dimension: Dimension, e: DragEvent) {
    var { essence, getUrlPrefix } = this.props;
    var dataTransfer = e.dataTransfer;
    dataTransfer.effectAllowed = 'all';

    if (getUrlPrefix) {
      var newUrl = essence.changeSplit(SplitCombine.fromExpression(dimension.expression), VisStrategy.FairGame).getURL(getUrlPrefix());
    try {
        dataTransfer.setData("text/url-list", newUrl);
        dataTransfer.setData("text/plain", newUrl);
      } catch (error) {
        //Don't need to do anything，Just for compatibility with Microsoft's edge browser
      }
    }

    DragManager.setDragDimension(dimension, 'dimension-list-tile');
    setDragGhost(dataTransfer, dimension.title);

    this.closeMenu();
  }

and I test in Microsoft's edge browser，it's work fine！

**Comment by beibm** [comment]
wow! I see it, thanks for your hard work!
