### ISSUE TITLE
Having an issue installing npm packages

### ISSUE THREAD

**Issue by johnrails** [allegro/turnilo#897]
My team is looking to integrate turnilo into an app we're working on. We're looking into using some of the components included. I'm trying to do some exploration but I'm unable to install the NPM packages. Each time i run `npm install` I get this error:

```
 integrity checksum failed when using sha512:
```
the log output says this:

```
19858 silly extract gauge@2.7.4
19859 verbose stack Error: sha512-<removed> integrity checksum failed when using sha512: wanted sha512-<removed> but got sha512-<removed>. (18042 bytes)
```
**removed the hash just because** 
I can install gauge `npm install gauge@2.7.4` just fine independently.

I'd appreciate any help.

Thanks!

**Comment by adrianmroz-allegro** [comment]
It sounds more like an issue with npm. I can't reproduce this issue.

Are you sure you using supported node/npm version (node 14.x would be best)?
Do you have some kind of proxy for npm in your company? 
Did you try to clean and/or verify your npm caches? `npm cache verify` and `npm cache clean --force`
If you're just looking around and don't want to contribute back, you can remove `package-lock.json` and install only of `package.lock`

**Comment by johnrails** [comment]
Thanks for getting back to me @adrianmroz-allegro i tried what you suggested but now i'm getting this.
I'm using node 14.19.x and npm 8.7x. I can probably fix this by installing the proper dependencies or just using `--legacy-peer-deps` but i just wanted to post this in case it's something that has been seen before.

```
turnilo git:(master) ✗ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: turnilo@1.35.1
npm ERR! Found: typescript@3.3.1
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"3.3.1" from the root project
npm ERR!   peer typescript@">=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev" from tslint@5.10.0
npm ERR!   node_modules/tslint
npm ERR!     dev tslint@"5.10.0" from the root project
npm ERR!     peer tslint@"^5.0.0" from tslint-eslint-rules@5.3.1
npm ERR!     node_modules/tslint-eslint-rules
npm ERR!       dev tslint-eslint-rules@"5.3.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^2.2.0" from tslint-eslint-rules@5.3.1
npm ERR! node_modules/tslint-eslint-rules
npm ERR!   dev tslint-eslint-rules@"5.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/j0d01w8/.npm/_logs/2022-04-26T16_40_38_845Z-debug-0.log
turnilo git:(master) ✗ npm -v
8.7.0
turnilo git:(master) ✗ node -v
v14.19.0
 turnilo git:(master) ✗
```

**Comment by johnrails** [comment]
I'm closing this. it's not an issue for me any more
