### ISSUE TITLE
App fails to start if installed with yarn

### ISSUE THREAD

**Issue by betalb** [allegro/turnilo#9]
When turnulo npm package is installed with yarn, it fails to start

This is caused by different algorithm for version hoisting

immutable-class package made API-breaking change in patch release, and removed static method `isInstanceOf` somewhere around version 0.6.20 (though 0 major version allows to do everything)

turnilo explicitly depends on 0.6.9 version of immutable class, but swiv-plywood depends on `0.6.x`, which causing issues when package is installed with yarn. It installes 0.6.42 for plywood and 0.6.9 for turnilo itself, but swiv-plywood 0.12.17 can't work with immutable-class 0.6.41

BTW I was not able to find a repo of swiv-plywood, npm page references original repository

**Comment by mkuthan** [comment]
Good point @betalb, thanks for reporting. Please look at #10 proposal, it should also resolve this issue.

**Comment by mkuthan** [comment]
@betalb - Turnilo starts when npm packages are installed using yarn. We are going to release Turnilo 1.1.0 next week.

**Comment by betalb** [comment]
Thank you. Upgrading plywood seems to be a better fix
