### ISSUE TITLE
null is string ?

### ISSUE THREAD

**Issue by Laboltus** [allegro/turnilo#904]
From time to time we get 500 error when use some specific set of measures and time shift. In broker response I see following error:
```
{
  "error": "Unknown exception",
  "errorMessage": "unsupported type STRING",
  "errorClass": "java.lang.IllegalArgumentException",
  "host": null
}

```
at the same time I see following error in historical log:

```
[ERROR] 2022-06-02 11:37:01,299 org.apache.druid.server.QueryResource logException - Unable to send query response. (com.fasterxml.jackson.databind.JsonMappingException: unsupported type STRING (through reference chain: org.apache.druid.query.Result["result"]->org.apache.druid.query.BySegmentResultValueClass["results"]->com.google.common.collect.Lists$TransformingRandomAccessList[0]))
[ERROR] 2022-06-02 11:37:01,299 org.apache.druid.server.QueryLifecycle logException - Exception while processing queryId [4485a8e9-34f8-47db-99f5-5940bf4fce32] (com.fasterxml.jackson.databind.JsonMappingException: unsupported type STRING (through reference chain: org.apache.druid.query.Result["result"]->org.apache.druid.query.BySegmentResultValueClass["results"]->com.google.common.collect.Lists$TransformingRandomAccessList[0]))
[WARN] 2022-06-02 11:37:01,301 org.eclipse.jetty.server.Http
```

I tried to localize what part of request triggers the error and here it is:

```
...
   "postAggregations":[
...
      {
         "type":"expression",
         "expression":"(if(\"!T_8\"!=0,(cast(\"!T_0\",'DOUBLE')/\"!T_8\"),null)-if(\"!T_9\"!=0,(cast(\"!T_4\",'DOUBLE')/\"!T_9\"),null))",
         "name":"_delta__media_cost_ecpc"
      },
...
```

If I replace any or both of 'null' with '0', the query works. Looks like the error appears in case of "expression":"null/null"

**Comment by Ans-hrfc** [comment]
Hi @Laboltus 

i'm running into a similar error. I saw you closed the issue have you been able to find a workaround so that turnilo doesn't use null ? thanks

**Comment by Laboltus** [comment]
In our case we found out that the expression's divisor can be null on some intervals. It's not a common situation, so it's just became a known issue in our workflow. I guess the function [fallback](https://plywood.imply.io/expressions#fallback) could be used as a workaround, but we haven't tested it.
