### ISSUE TITLE
Configurable TimeMonitor interval

### ISSUE THREAD

**Issue by boaz-wiesner** [allegro/turnilo#925]
At the moment, the TimeMonitor interval is hardcoded to 1 minute. In druid clusters with many datasources, running a full cycle of time checks can take longer than a minute, and lead to continuous polling of the cluster, which isn't optimal.

Moving this to a cluster level configurable parameter would definitely solve the problem.

The relevant line seems to be:
https://github.com/allegro/turnilo/blob/f8c7af2a0ed5a251fb3f4db7d6d734fdc07347da/src/common/utils/time-monitor/time-monitor.ts#L36

Thanks!

**Comment by boaz-wiesner** [comment]
Another default that is currently hardcoded is the default "time" metric (timeAttribute). Introspected sources end up using this default, and currently there's no way to configure it.

Allowing this default to be changed cluster-wide would enable automatic introspection of datasources not using `__time` as their field. At the moment, if you have an introspected source with a different field, it won't work.

https://github.com/allegro/turnilo/blob/a78295adcee3a44527dcf262f3a6752845f92c1d/src/common/models/data-cube/data-cube.ts#L291

**Comment by adrianmroz-allegro** [comment]
I think cluster level property in config for `regularCheckInterval` sounds good. As always we need to figure out good name. `sourceMaxTimeRefreshInterval`? `MaxTime` is turnilo centric, that how we talk about it in codebase. Maybe there is better term in Druid lingo? @mkuthan wanna weigh in? `sourceTimeBoundaryRefreshInterval`?

**Comment by adrianmroz-allegro** [comment]
> Another default that is currently hardcoded is the default "time" dimension (`timeAttribute`).

That's deliberate. To my understanding `__time` attribute name is required by Druid. It is a special dimension used to partition data. In theory you could have additional "time" dimensions but turnilo can't work with them, we handle only one time dimension that's partitioning column.

**Comment by boaz-wiesner** [comment]
>As always we need to figure out good name. `sourceMaxTimeRefreshInterval`? `MaxTime` is turnilo centric, that how we talk about it in codebase. Maybe there is better term in Druid lingo? `sourceTimeBoundaryRefreshInterval`?

I'm for something like `timeBoundaryQueryInterval` or `sourceTimeBoundaryRefreshInterval`, but as long as the name is documented then I don't have a strong opinion one way or the other.

> That's deliberate. To my understanding `__time` attribute name is required by Druid

Yep, my bad - we use alternative fields for additional partitioning and applicative uses, but for Turnilo's use case of running a TimeBoundary query it should be enough.
