### ISSUE TITLE
Cannot change split data source threshold

### ISSUE THREAD

**Issue by johngeorgewright** [allegro/turnilo#928]
Version: 1.37.0

I can't seem to limit a split data source to anything greater than 10.

<img width="475" alt="Screenshot 2022-11-07 at 13 05 14" src="https://user-images.githubusercontent.com/1423566/200317608-20fb5245-b844-483c-8faf-1c8b0ed9bb79.png">

Choosing anything higher will always result in a query where the "threshold" is set to 10.

**Comment by adrianmroz-allegro** [comment]
That's a "feature". But a feature with really bad UI.
You selected Line Chart visualisation and there, second split is limited to 10 because we only have 10 colours to distinguish lines on the chart. 

Ideally UI should show only options from range [0, 10]. That's something we should implement.

**Comment by johngeorgewright** [comment]
I see. We'd really like the option to have more lines. Is there any chance the colour list could be configurable for situations like ours?

**Comment by adrianmroz-allegro** [comment]
I just duplicated colour list in config and got split with limit 20 elements: 
![Screenshot 2022-11-30 at 16 35 21](https://user-images.githubusercontent.com/78143552/204841133-00a65583-5cf4-4399-bb4d-e8f6c54bcdf5.png)

**Comment by adrianmroz-allegro** [comment]
Should be fixed in current beta. I'll close for now, if you find any bugs or have any concerns, reopen.
