### ISSUE TITLE
Mini scroll bar on each selection in filter menu

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#929]
Regression is probably introduced in 5d77473d92e0d5c1bbddc44edf765ebbe73633d5.

<img width="539" alt="double-scroll" src="https://user-images.githubusercontent.com/14329097/200837939-a14063b2-7623-4a6f-90d5-a68582803480.png">

**Comment by l2dy** [comment]
Chrome 107 on macOS with mouse plugged in.

**Comment by adrianmroz-allegro** [comment]
Damn, I have similar setup and don't see that. 

Are you feeling adventurous and want to fiddle with CSS and contribute? `overflow-y: hidden` or something like that could work?

**Comment by l2dy** [comment]
`overflow-y: hidden` on `.string-value .value-wrapper` seems to fix it.

The problem was introduced by `top: 1px` in `.string-value .value-wrapper .checkbox`. Removing it could also fix the issue.

**Comment by adrianmroz-allegro** [comment]
Ok, I managed to reproduce it. You have "Always show scrollbars" setting in macOS. Fix should land with next version quite soon.

**Comment by adrianmroz-allegro** [comment]
I was wondering why boolean filters don't show scrollbar but string do. Apparently, changing overflow-x affects overflow-y property default value.
