### ISSUE TITLE
 Integrate Turnilo with Apache Superset?

### ISSUE THREAD

**Issue by sanoopmm** [allegro/turnilo#97]
Can I integrate Turnilo with Apache Superset? Is there any possible way currently to do so and in the absence of it, can I do this with minimum coding effort?

**Comment by mkuthan** [comment]
@sanoopmm What do you mean, integrate?

**Comment by sanoopmm** [comment]
Can I use the tables(as datasource) in superset to create data cubes in Turnilo. Basically I need to visualize the superset tables using Turnilo. Both these tools support Druid, Can I use druid store or any other possible way to combine these tools? Apache superset is using Sqlalchemy, Does Turnilo supports Sqlalchemy ?

**Comment by mkuthan** [comment]
What kind of "superset tables" do you mean? There are only slices/charts combined into dashboards.

SQLAlchemy is a Python library, could you check the programming language of Turnilo project before asking this kind of questions?
